/* -*-  mode:c; tab-width:8; c-basic-offset:8; indent-tabs-mode:nil;  -*- */
/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * AUTO-GENERATED by idlcomp.py from winreg.idl — do not edit.
 */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif

#ifdef HAVE_STDINT_H
#include <stdint.h>
#endif

#ifdef HAVE_STDLIB_H
#include <stdlib.h>
#endif

#ifdef HAVE_STRING_H
#include <string.h>
#endif

#ifdef STDC_HEADERS
#include <stddef.h>
#endif

#ifdef HAVE_SYS_TYPES_H
#include <sys/types.h>
#endif

#ifdef HAVE_SYS_STAT_H
#include <sys/stat.h>
#endif

#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif

#ifdef HAVE_SYS_UNISTD_H
#include <sys/unistd.h>
#endif

#include <errno.h>
#include <stdio.h>


#include <smb2/smb2.h>
#include <smb2/libsmb2.h>
#include <dcerpc/dcerpc.h>
#include <dcerpc/dcerpc-dtyp.h>
#include <dcerpc/dcerpc-winreg.h>
#include <smb2/libsmb2-raw.h>
#include "dcerpc-private.h"

#define WINREG_UUID    0x338cd001, 0x2244, 0x31f1, {0xaa, 0xaa, 0x90, 0x00, 0x38, 0x00, 0x10, 0x03}

p_syntax_id_t winreg_interface = {
        {WINREG_UUID}, 1, 0
};

static int winreg_uint16_t_ptr_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
static int winreg_RPC_SECURITY_ATTRIBUTES_ptr_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
static int winreg_FILETIME_ptr_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
static int
winreg_uint16_t_ptr_coder(char *name, struct dcerpc_context *dce,
                     struct dcerpc_pdu *pdu,
                     struct dcerpc_iovec *iov, int *offset,
                     void *ptr)
{
        uint16_t **pp = ptr;

        if (dcerpc_pdu_direction(pdu) == DCERPC_DECODE && *pp == NULL) {
                *pp = dcerpc_alloc_data(pdu, sizeof(**pp));
                if (*pp == NULL) {
                        return -1;
                }
        }
        return dcerpc_uint16_coder(name, dce, pdu, iov, offset, *pp);
}

static int
winreg_RPC_SECURITY_ATTRIBUTES_ptr_coder(char *name, struct dcerpc_context *dce,
                     struct dcerpc_pdu *pdu,
                     struct dcerpc_iovec *iov, int *offset,
                     void *ptr)
{
        struct winreg_RPC_SECURITY_ATTRIBUTES **pp = ptr;

        if (dcerpc_pdu_direction(pdu) == DCERPC_DECODE && *pp == NULL) {
                *pp = dcerpc_alloc_data(pdu, sizeof(**pp));
                if (*pp == NULL) {
                        return -1;
                }
        }
        return winreg_RPC_SECURITY_ATTRIBUTES_struct_coder(name, dce, pdu, iov, offset, *pp);
}

static int
winreg_FILETIME_ptr_coder(char *name, struct dcerpc_context *dce,
                     struct dcerpc_pdu *pdu,
                     struct dcerpc_iovec *iov, int *offset,
                     void *ptr)
{
        struct winreg_FILETIME **pp = ptr;

        if (dcerpc_pdu_direction(pdu) == DCERPC_DECODE && *pp == NULL) {
                *pp = dcerpc_alloc_data(pdu, sizeof(**pp));
                if (*pp == NULL) {
                        return -1;
                }
        }
        return winreg_FILETIME_struct_coder(name, dce, pdu, iov, offset, *pp);
}

static int
winreg_RPC_HKEY_param_coder(char *name, struct dcerpc_context *dce,
                     struct dcerpc_pdu *pdu,
                     struct dcerpc_iovec *iov, int *offset,
                     void *ptr)
{
        return dcerpc_struct_coder(name, dce, pdu, iov, offset, ptr,
                                   dcerpc_context_handle_coder);
}

/* REGSAM: NDR uint32; YAML/JSON show the flag names */
static struct dcerpc_uint32_pretty_printer winreg_REGSAM_pp = {
        .fmt = "0x%08x",
        .bitfields = {
                { "KEY_QUERY_VALUE", WINREG_KEY_QUERY_VALUE, WINREG_KEY_QUERY_VALUE },
                { "KEY_SET_VALUE", WINREG_KEY_SET_VALUE, WINREG_KEY_SET_VALUE },
                { "KEY_CREATE_SUB_KEY", WINREG_KEY_CREATE_SUB_KEY, WINREG_KEY_CREATE_SUB_KEY },
                { "KEY_ENUMERATE_SUB_KEYS", WINREG_KEY_ENUMERATE_SUB_KEYS, WINREG_KEY_ENUMERATE_SUB_KEYS },
                { "KEY_NOTIFY", WINREG_KEY_NOTIFY, WINREG_KEY_NOTIFY },
                { "KEY_CREATE_LINK", WINREG_KEY_CREATE_LINK, WINREG_KEY_CREATE_LINK },
                { "KEY_WOW64_64KEY", WINREG_KEY_WOW64_64KEY, WINREG_KEY_WOW64_64KEY },
                { "KEY_WOW64_32KEY", WINREG_KEY_WOW64_32KEY, WINREG_KEY_WOW64_32KEY },
                { "DELETE", WINREG_DELETE, WINREG_DELETE },
                { "READ_CONTROL", WINREG_READ_CONTROL, WINREG_READ_CONTROL },
                { "WRITE_DAC", WINREG_WRITE_DAC, WINREG_WRITE_DAC },
                { "WRITE_OWNER", WINREG_WRITE_OWNER, WINREG_WRITE_OWNER },
                { "SYNCHRONIZE", WINREG_SYNCHRONIZE, WINREG_SYNCHRONIZE },
                { "KEY_READ", WINREG_KEY_READ, WINREG_KEY_READ },
                { "KEY_WRITE", WINREG_KEY_WRITE, WINREG_KEY_WRITE },
                { "KEY_ALL_ACCESS", WINREG_KEY_ALL_ACCESS, WINREG_KEY_ALL_ACCESS },
                { NULL, 0, 0 },
        },
};

int
winreg_REGSAM_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_uint32_coder_pp(name, dce, pdu, iov, offset, ptr,
                                      &winreg_REGSAM_pp);
}

/* REG_OPTIONS: NDR uint32; YAML/JSON show the flag names */
static struct dcerpc_uint32_pretty_printer winreg_REG_OPTIONS_pp = {
        .fmt = "0x%08x",
        .bitfields = {
                { "REG_OPTION_NON_VOLATILE", 0xffffffff, WINREG_REG_OPTION_NON_VOLATILE },
                { "REG_OPTION_VOLATILE", WINREG_REG_OPTION_VOLATILE, WINREG_REG_OPTION_VOLATILE },
                { "REG_OPTION_CREATE_LINK", WINREG_REG_OPTION_CREATE_LINK, WINREG_REG_OPTION_CREATE_LINK },
                { "REG_OPTION_BACKUP_RESTORE", WINREG_REG_OPTION_BACKUP_RESTORE, WINREG_REG_OPTION_BACKUP_RESTORE },
                { "REG_OPTION_OPEN_LINK", WINREG_REG_OPTION_OPEN_LINK, WINREG_REG_OPTION_OPEN_LINK },
                { NULL, 0, 0 },
        },
};

int
winreg_REG_OPTIONS_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_uint32_coder_pp(name, dce, pdu, iov, offset, ptr,
                                      &winreg_REG_OPTIONS_pp);
}

/* REG_DISPOSITION: NDR uint32; YAML/JSON show the value names */
static struct dcerpc_uint32_pretty_printer winreg_REG_DISPOSITION_pp = {
        .fmt = "%u",
        .bitfields = {
                { "REG_CREATED_NEW_KEY", 0xffffffff, WINREG_REG_CREATED_NEW_KEY },
                { "REG_OPENED_EXISTING_KEY", 0xffffffff, WINREG_REG_OPENED_EXISTING_KEY },
                { NULL, 0, 0 },
        },
};

int
winreg_REG_DISPOSITION_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_uint32_coder_pp(name, dce, pdu, iov, offset, ptr,
                                      &winreg_REG_DISPOSITION_pp);
}

/* REG_VALUE_TYPE: NDR uint32; YAML/JSON show the value names */
static struct dcerpc_uint32_pretty_printer winreg_REG_VALUE_TYPE_pp = {
        .fmt = "%u",
        .bitfields = {
                { "REG_NONE", 0xffffffff, WINREG_REG_NONE },
                { "REG_SZ", 0xffffffff, WINREG_REG_SZ },
                { "REG_EXPAND_SZ", 0xffffffff, WINREG_REG_EXPAND_SZ },
                { "REG_BINARY", 0xffffffff, WINREG_REG_BINARY },
                { "REG_DWORD", 0xffffffff, WINREG_REG_DWORD },
                { "REG_DWORD_BIG_ENDIAN", 0xffffffff, WINREG_REG_DWORD_BIG_ENDIAN },
                { "REG_LINK", 0xffffffff, WINREG_REG_LINK },
                { "REG_MULTI_SZ", 0xffffffff, WINREG_REG_MULTI_SZ },
                { "REG_RESOURCE_LIST", 0xffffffff, WINREG_REG_RESOURCE_LIST },
                { "REG_FULL_RESOURCE_DESCRIPTOR", 0xffffffff, WINREG_REG_FULL_RESOURCE_DESCRIPTOR },
                { "REG_RESOURCE_REQUIREMENTS_LIST", 0xffffffff, WINREG_REG_RESOURCE_REQUIREMENTS_LIST },
                { "REG_QWORD", 0xffffffff, WINREG_REG_QWORD },
                { NULL, 0, 0 },
        },
};

int
winreg_REG_VALUE_TYPE_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_uint32_coder_pp(name, dce, pdu, iov, offset, ptr,
                                      &winreg_REG_VALUE_TYPE_pp);
}

int
winreg_FILETIME_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_FILETIME *s = ptr;

        (void)name;
        if (dcerpc_uint32_coder("dwLowDateTime", dce, pdu, iov, offset, &s->dwLowDateTime)) {
                return -1;
        }
        if (dcerpc_uint32_coder("dwHighDateTime", dce, pdu, iov, offset, &s->dwHighDateTime)) {
                return -1;
        }

        return 0;
}

int
winreg_FILETIME_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_struct_coder(name, dce, pdu, iov, offset, ptr,
                                   winreg_FILETIME_coder);
}

int
winreg_RPC_SECURITY_DESCRIPTOR_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_RPC_SECURITY_DESCRIPTOR *s = ptr;

        (void)name;
        if (dcerpc_ptr_coder("lpSecurityDescriptor", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE &&
                              s->lpSecurityDescriptor.data == NULL) ? NULL : &s->lpSecurityDescriptor,
                             PTR_UNIQUE, dcerpc_varying_bytes_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("cbInSecurityDescriptor", dce, pdu, iov, offset, &s->cbInSecurityDescriptor)) {
                return -1;
        }
        if (dcerpc_uint32_coder("cbOutSecurityDescriptor", dce, pdu, iov, offset, &s->cbOutSecurityDescriptor)) {
                return -1;
        }

        return 0;
}

int
winreg_RPC_SECURITY_DESCRIPTOR_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_struct_coder(name, dce, pdu, iov, offset, ptr,
                                   winreg_RPC_SECURITY_DESCRIPTOR_coder);
}

int
winreg_RPC_SECURITY_ATTRIBUTES_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_RPC_SECURITY_ATTRIBUTES *s = ptr;

        (void)name;
        if (dcerpc_uint32_coder("nLength", dce, pdu, iov, offset, &s->nLength)) {
                return -1;
        }
        if (winreg_RPC_SECURITY_DESCRIPTOR_coder("RpcSecurityDescriptor", dce, pdu, iov, offset, &s->RpcSecurityDescriptor)) {
                return -1;
        }
        if (dcerpc_uint8_coder("bInheritHandle", dce, pdu, iov, offset, &s->bInheritHandle)) {
                return -1;
        }

        return 0;
}

int
winreg_RPC_SECURITY_ATTRIBUTES_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_struct_coder(name, dce, pdu, iov, offset, ptr,
                                   winreg_RPC_SECURITY_ATTRIBUTES_coder);
}

/*****************
 * Function: 0x00  OpenClassesRoot  (WINREG_OPENCLASSESROOT)
 *****************/
int
winreg_OpenClassesRoot_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_OpenClassesRoot_req *req = ptr;

        (void)name;
        if (dcerpc_ptr_coder("ServerName", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE &&
                              req->ServerName == NULL) ? NULL : &req->ServerName,
                             PTR_UNIQUE, winreg_uint16_t_ptr_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("samDesired", dce, pdu, iov, offset, &req->samDesired,
                             PTR_REF, winreg_REGSAM_coder)) {
                return -1;
        }

        return 0;
}

int
winreg_OpenClassesRoot_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_OpenClassesRoot_rep *rep = ptr;

        (void)name;
        if (dcerpc_ptr_coder("phKey", dce, pdu, iov, offset, &rep->phKey,
                             PTR_REF, winreg_RPC_HKEY_param_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/*****************
 * Function: 0x01  OpenCurrentUser  (WINREG_OPENCURRENTUSER)
 *****************/
int
winreg_OpenCurrentUser_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_OpenCurrentUser_req *req = ptr;

        (void)name;
        if (dcerpc_ptr_coder("ServerName", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE &&
                              req->ServerName == NULL) ? NULL : &req->ServerName,
                             PTR_UNIQUE, winreg_uint16_t_ptr_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("samDesired", dce, pdu, iov, offset, &req->samDesired,
                             PTR_REF, winreg_REGSAM_coder)) {
                return -1;
        }

        return 0;
}

int
winreg_OpenCurrentUser_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_OpenCurrentUser_rep *rep = ptr;

        (void)name;
        if (dcerpc_ptr_coder("phKey", dce, pdu, iov, offset, &rep->phKey,
                             PTR_REF, winreg_RPC_HKEY_param_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/*****************
 * Function: 0x02  OpenLocalMachine  (WINREG_OPENLOCALMACHINE)
 *****************/
int
winreg_OpenLocalMachine_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_OpenLocalMachine_req *req = ptr;

        (void)name;
        if (dcerpc_ptr_coder("ServerName", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE &&
                              req->ServerName == NULL) ? NULL : &req->ServerName,
                             PTR_UNIQUE, winreg_uint16_t_ptr_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("samDesired", dce, pdu, iov, offset, &req->samDesired,
                             PTR_REF, winreg_REGSAM_coder)) {
                return -1;
        }

        return 0;
}

int
winreg_OpenLocalMachine_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_OpenLocalMachine_rep *rep = ptr;

        (void)name;
        if (dcerpc_ptr_coder("phKey", dce, pdu, iov, offset, &rep->phKey,
                             PTR_REF, winreg_RPC_HKEY_param_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/*****************
 * Function: 0x04  OpenUsers  (WINREG_OPENUSERS)
 *****************/
int
winreg_OpenUsers_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_OpenUsers_req *req = ptr;

        (void)name;
        if (dcerpc_ptr_coder("ServerName", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE &&
                              req->ServerName == NULL) ? NULL : &req->ServerName,
                             PTR_UNIQUE, winreg_uint16_t_ptr_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("samDesired", dce, pdu, iov, offset, &req->samDesired,
                             PTR_REF, winreg_REGSAM_coder)) {
                return -1;
        }

        return 0;
}

int
winreg_OpenUsers_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_OpenUsers_rep *rep = ptr;

        (void)name;
        if (dcerpc_ptr_coder("phKey", dce, pdu, iov, offset, &rep->phKey,
                             PTR_REF, winreg_RPC_HKEY_param_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/*****************
 * Function: 0x05  BaseRegCloseKey  (WINREG_BASEREGCLOSEKEY)
 *****************/
int
winreg_BaseRegCloseKey_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegCloseKey_req *req = ptr;

        (void)name;
        if (dcerpc_ptr_coder("hKey", dce, pdu, iov, offset, &req->hKey,
                             PTR_REF, winreg_RPC_HKEY_param_coder)) {
                return -1;
        }

        return 0;
}

int
winreg_BaseRegCloseKey_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegCloseKey_rep *rep = ptr;

        (void)name;
        if (dcerpc_ptr_coder("hKey", dce, pdu, iov, offset, &rep->hKey,
                             PTR_REF, winreg_RPC_HKEY_param_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/*****************
 * Function: 0x06  BaseRegCreateKey  (WINREG_BASEREGCREATEKEY)
 *****************/
int
winreg_BaseRegCreateKey_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegCreateKey_req *req = ptr;

        (void)name;
        if (dcerpc_ptr_coder("hKey", dce, pdu, iov, offset, &req->hKey,
                             PTR_REF, winreg_RPC_HKEY_param_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpSubKey", dce, pdu, iov, offset, &req->lpSubKey,
                             PTR_REF, dcerpc_RPC_UNICODE_STRINGz_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpClass", dce, pdu, iov, offset, &req->lpClass,
                             PTR_REF, dcerpc_RPC_UNICODE_STRINGz_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("dwOptions", dce, pdu, iov, offset, &req->dwOptions,
                             PTR_REF, winreg_REG_OPTIONS_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("samDesired", dce, pdu, iov, offset, &req->samDesired,
                             PTR_REF, winreg_REGSAM_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpSecurityAttributes", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE &&
                              req->lpSecurityAttributes == NULL) ? NULL : &req->lpSecurityAttributes,
                             PTR_UNIQUE, winreg_RPC_SECURITY_ATTRIBUTES_ptr_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpdwDisposition", dce, pdu, iov, offset, &req->lpdwDisposition,
                             PTR_UNIQUE, winreg_REG_DISPOSITION_coder)) {
                return -1;
        }

        return 0;
}

int
winreg_BaseRegCreateKey_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegCreateKey_rep *rep = ptr;

        (void)name;
        if (dcerpc_ptr_coder("phkResult", dce, pdu, iov, offset, &rep->phkResult,
                             PTR_REF, winreg_RPC_HKEY_param_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpdwDisposition", dce, pdu, iov, offset, &rep->lpdwDisposition,
                             PTR_UNIQUE, winreg_REG_DISPOSITION_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/*****************
 * Function: 0x07  BaseRegDeleteKey  (WINREG_BASEREGDELETEKEY)
 *****************/
int
winreg_BaseRegDeleteKey_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegDeleteKey_req *req = ptr;

        (void)name;
        if (dcerpc_ptr_coder("hKey", dce, pdu, iov, offset, &req->hKey,
                             PTR_REF, winreg_RPC_HKEY_param_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpSubKey", dce, pdu, iov, offset, &req->lpSubKey,
                             PTR_REF, dcerpc_RPC_UNICODE_STRINGz_coder)) {
                return -1;
        }

        return 0;
}

int
winreg_BaseRegDeleteKey_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegDeleteKey_rep *rep = ptr;

        (void)name;
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/*****************
 * Function: 0x08  BaseRegDeleteValue  (WINREG_BASEREGDELETEVALUE)
 *****************/
int
winreg_BaseRegDeleteValue_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegDeleteValue_req *req = ptr;

        (void)name;
        if (dcerpc_ptr_coder("hKey", dce, pdu, iov, offset, &req->hKey,
                             PTR_REF, winreg_RPC_HKEY_param_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpValueName", dce, pdu, iov, offset, &req->lpValueName,
                             PTR_REF, dcerpc_RPC_UNICODE_STRINGz_coder)) {
                return -1;
        }

        return 0;
}

int
winreg_BaseRegDeleteValue_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegDeleteValue_rep *rep = ptr;

        (void)name;
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/*****************
 * Function: 0x09  BaseRegEnumKey  (WINREG_BASEREGENUMKEY)
 *****************/
int
winreg_BaseRegEnumKey_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegEnumKey_req *req = ptr;

        (void)name;
        if (dcerpc_ptr_coder("hKey", dce, pdu, iov, offset, &req->hKey,
                             PTR_REF, winreg_RPC_HKEY_param_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("dwIndex", dce, pdu, iov, offset, &req->dwIndex,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }
        dcerpc_set_unicode_max_length(pdu, 1024);
        if (dcerpc_ptr_coder("lpNameIn", dce, pdu, iov, offset, &req->lpNameIn,
                             PTR_REF, dcerpc_RPC_UNICODE_STRING_coder)) {
                return -1;
        }
        dcerpc_set_unicode_max_length(pdu, 128);
        if (dcerpc_ptr_coder("lpClassIn", dce, pdu, iov, offset, &req->lpClassIn,
                             PTR_UNIQUE, dcerpc_RPC_UNICODE_STRING_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpftLastWriteTime", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE &&
                              req->lpftLastWriteTime == NULL) ? NULL : &req->lpftLastWriteTime,
                             PTR_UNIQUE, winreg_FILETIME_ptr_coder)) {
                return -1;
        }

        return 0;
}

int
winreg_BaseRegEnumKey_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegEnumKey_rep *rep = ptr;

        (void)name;
        if (dcerpc_ptr_coder("lpNameOut", dce, pdu, iov, offset, &rep->lpNameOut,
                             PTR_REF, dcerpc_RPC_UNICODE_STRINGz_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lplpClassOut", dce, pdu, iov, offset, &rep->lplpClassOut,
                             PTR_UNIQUE, dcerpc_RPC_UNICODE_STRINGz_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpftLastWriteTime", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE &&
                              rep->lpftLastWriteTime == NULL) ? NULL : &rep->lpftLastWriteTime,
                             PTR_UNIQUE, winreg_FILETIME_ptr_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/*****************
 * Function: 0x0a  BaseRegEnumValue  (WINREG_BASEREGENUMVALUE)
 *****************/
int
winreg_BaseRegEnumValue_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegEnumValue_req *req = ptr;

        (void)name;
        if (dcerpc_ptr_coder("hKey", dce, pdu, iov, offset, &req->hKey,
                             PTR_REF, winreg_RPC_HKEY_param_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("dwIndex", dce, pdu, iov, offset, &req->dwIndex,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }
        dcerpc_set_unicode_max_length(pdu, 1024);
        if (dcerpc_ptr_coder("lpValueNameIn", dce, pdu, iov, offset, &req->lpValueNameIn,
                             PTR_REF, dcerpc_RPC_UNICODE_STRING_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpType", dce, pdu, iov, offset, &req->lpType,
                             PTR_UNIQUE, winreg_REG_VALUE_TYPE_coder)) {
                return -1;
        }
        {
                struct dcerpc_varying_bytes vb;

                vb.max_count = req->lpcbData;
                vb.len = req->lpcbLen;
                vb.data = req->lpData;
                if (dcerpc_ptr_coder("lpData", dce, pdu, iov, offset, &vb,
                                     PTR_UNIQUE, dcerpc_varying_bytes_coder)) {
                        return -1;
                }
                if (dcerpc_pdu_direction(pdu) == DCERPC_DECODE) {
                        req->lpData = vb.data;
                }
        }
        if (dcerpc_ptr_coder("lpcbData", dce, pdu, iov, offset, &req->lpcbData,
                             PTR_UNIQUE, dcerpc_uint32_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpcbLen", dce, pdu, iov, offset, &req->lpcbLen,
                             PTR_UNIQUE, dcerpc_uint32_coder)) {
                return -1;
        }

        return 0;
}

int
winreg_BaseRegEnumValue_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegEnumValue_rep *rep = ptr;

        (void)name;
        if (dcerpc_ptr_coder("lpValueNameOut", dce, pdu, iov, offset, &rep->lpValueNameOut,
                             PTR_REF, dcerpc_RPC_UNICODE_STRINGz_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpType", dce, pdu, iov, offset, &rep->lpType,
                             PTR_UNIQUE, winreg_REG_VALUE_TYPE_coder)) {
                return -1;
        }
        {
                struct dcerpc_varying_bytes vb;

                vb.max_count = rep->lpcbData;
                vb.len = rep->lpcbLen;
                vb.data = rep->lpData;
                if (dcerpc_ptr_coder("lpData", dce, pdu, iov, offset, &vb,
                                     PTR_UNIQUE, dcerpc_varying_bytes_coder)) {
                        return -1;
                }
                if (dcerpc_pdu_direction(pdu) == DCERPC_DECODE) {
                        rep->lpData = vb.data;
                }
        }
        if (dcerpc_ptr_coder("lpcbData", dce, pdu, iov, offset, &rep->lpcbData,
                             PTR_UNIQUE, dcerpc_uint32_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpcbLen", dce, pdu, iov, offset, &rep->lpcbLen,
                             PTR_UNIQUE, dcerpc_uint32_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/*****************
 * Function: 0x0f  BaseRegOpenKey  (WINREG_BASEREGOPENKEY)
 *****************/
int
winreg_BaseRegOpenKey_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegOpenKey_req *req = ptr;

        (void)name;
        if (dcerpc_ptr_coder("hKey", dce, pdu, iov, offset, &req->hKey,
                             PTR_REF, winreg_RPC_HKEY_param_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpSubKey", dce, pdu, iov, offset, &req->lpSubKey,
                             PTR_REF, dcerpc_RPC_UNICODE_STRINGz_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("dwOptions", dce, pdu, iov, offset, &req->dwOptions,
                             PTR_REF, winreg_REG_OPTIONS_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("samDesired", dce, pdu, iov, offset, &req->samDesired,
                             PTR_REF, winreg_REGSAM_coder)) {
                return -1;
        }

        return 0;
}

int
winreg_BaseRegOpenKey_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegOpenKey_rep *rep = ptr;

        (void)name;
        if (dcerpc_ptr_coder("phkResult", dce, pdu, iov, offset, &rep->phkResult,
                             PTR_REF, winreg_RPC_HKEY_param_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/*****************
 * Function: 0x10  BaseRegQueryInfoKey  (WINREG_BASEREGQUERYINFOKEY)
 *****************/
int
winreg_BaseRegQueryInfoKey_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegQueryInfoKey_req *req = ptr;

        (void)name;
        if (dcerpc_ptr_coder("hKey", dce, pdu, iov, offset, &req->hKey,
                             PTR_REF, winreg_RPC_HKEY_param_coder)) {
                return -1;
        }
        dcerpc_set_unicode_max_length(pdu, 128);
        if (dcerpc_ptr_coder("lpClassIn", dce, pdu, iov, offset, &req->lpClassIn,
                             PTR_REF, dcerpc_RPC_UNICODE_STRING_coder)) {
                return -1;
        }

        return 0;
}

int
winreg_BaseRegQueryInfoKey_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegQueryInfoKey_rep *rep = ptr;

        (void)name;
        if (dcerpc_ptr_coder("lpClassOut", dce, pdu, iov, offset, &rep->lpClassOut,
                             PTR_REF, dcerpc_RPC_UNICODE_STRINGz_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpcSubKeys", dce, pdu, iov, offset, &rep->lpcSubKeys,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpcbMaxSubKeyLen", dce, pdu, iov, offset, &rep->lpcbMaxSubKeyLen,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpcbMaxClassLen", dce, pdu, iov, offset, &rep->lpcbMaxClassLen,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpcValues", dce, pdu, iov, offset, &rep->lpcValues,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpcbMaxValueNameLen", dce, pdu, iov, offset, &rep->lpcbMaxValueNameLen,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpcbMaxValueLen", dce, pdu, iov, offset, &rep->lpcbMaxValueLen,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpcbSecurityDescriptor", dce, pdu, iov, offset, &rep->lpcbSecurityDescriptor,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpftLastWriteTime", dce, pdu, iov, offset, &rep->lpftLastWriteTime,
                             PTR_REF, winreg_FILETIME_struct_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/*****************
 * Function: 0x16  BaseRegSetValue  (WINREG_BASEREGSETVALUE)
 *****************/
int
winreg_BaseRegSetValue_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegSetValue_req *req = ptr;

        (void)name;
        if (dcerpc_ptr_coder("hKey", dce, pdu, iov, offset, &req->hKey,
                             PTR_REF, winreg_RPC_HKEY_param_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("lpValueName", dce, pdu, iov, offset, &req->lpValueName,
                             PTR_REF, dcerpc_RPC_UNICODE_STRINGz_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("dwType", dce, pdu, iov, offset, &req->dwType,
                             PTR_REF, winreg_REG_VALUE_TYPE_coder)) {
                return -1;
        }
        {
                struct dcerpc_bytes bytes;

                bytes.len = req->cbData;
                bytes.data = req->lpData;
                if (dcerpc_bytes_coder("lpData", dce, pdu, iov, offset, &bytes)) {
                        return -1;
                }
                if (dcerpc_pdu_direction(pdu) == DCERPC_DECODE) {
                        req->lpData = bytes.data;
                }
        }
        if (dcerpc_ptr_coder("cbData", dce, pdu, iov, offset, &req->cbData,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }

        return 0;
}

int
winreg_BaseRegSetValue_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_BaseRegSetValue_rep *rep = ptr;

        (void)name;
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/*****************
 * Function: 0x1b  OpenCurrentConfig  (WINREG_OPENCURRENTCONFIG)
 *****************/
int
winreg_OpenCurrentConfig_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_OpenCurrentConfig_req *req = ptr;

        (void)name;
        if (dcerpc_ptr_coder("ServerName", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE &&
                              req->ServerName == NULL) ? NULL : &req->ServerName,
                             PTR_UNIQUE, winreg_uint16_t_ptr_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("samDesired", dce, pdu, iov, offset, &req->samDesired,
                             PTR_REF, winreg_REGSAM_coder)) {
                return -1;
        }

        return 0;
}

int
winreg_OpenCurrentConfig_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct winreg_OpenCurrentConfig_rep *rep = ptr;

        (void)name;
        if (dcerpc_ptr_coder("phKey", dce, pdu, iov, offset, &rep->phKey,
                             PTR_REF, winreg_RPC_HKEY_param_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/* Procedure table: opnum → request/response coders and sizes */
struct dcerpc_procedure winreg_procs[] = {
        {WINREG_OPENCLASSESROOT, "OpenClassesRoot",
         winreg_OpenClassesRoot_req_coder, sizeof(struct winreg_OpenClassesRoot_req),
         winreg_OpenClassesRoot_rep_coder, sizeof(struct winreg_OpenClassesRoot_rep),
        },
        {WINREG_OPENCURRENTUSER, "OpenCurrentUser",
         winreg_OpenCurrentUser_req_coder, sizeof(struct winreg_OpenCurrentUser_req),
         winreg_OpenCurrentUser_rep_coder, sizeof(struct winreg_OpenCurrentUser_rep),
        },
        {WINREG_OPENLOCALMACHINE, "OpenLocalMachine",
         winreg_OpenLocalMachine_req_coder, sizeof(struct winreg_OpenLocalMachine_req),
         winreg_OpenLocalMachine_rep_coder, sizeof(struct winreg_OpenLocalMachine_rep),
        },
        {WINREG_OPENUSERS, "OpenUsers",
         winreg_OpenUsers_req_coder, sizeof(struct winreg_OpenUsers_req),
         winreg_OpenUsers_rep_coder, sizeof(struct winreg_OpenUsers_rep),
        },
        {WINREG_BASEREGCLOSEKEY, "BaseRegCloseKey",
         winreg_BaseRegCloseKey_req_coder, sizeof(struct winreg_BaseRegCloseKey_req),
         winreg_BaseRegCloseKey_rep_coder, sizeof(struct winreg_BaseRegCloseKey_rep),
        },
        {WINREG_BASEREGCREATEKEY, "BaseRegCreateKey",
         winreg_BaseRegCreateKey_req_coder, sizeof(struct winreg_BaseRegCreateKey_req),
         winreg_BaseRegCreateKey_rep_coder, sizeof(struct winreg_BaseRegCreateKey_rep),
        },
        {WINREG_BASEREGDELETEKEY, "BaseRegDeleteKey",
         winreg_BaseRegDeleteKey_req_coder, sizeof(struct winreg_BaseRegDeleteKey_req),
         winreg_BaseRegDeleteKey_rep_coder, sizeof(struct winreg_BaseRegDeleteKey_rep),
        },
        {WINREG_BASEREGDELETEVALUE, "BaseRegDeleteValue",
         winreg_BaseRegDeleteValue_req_coder, sizeof(struct winreg_BaseRegDeleteValue_req),
         winreg_BaseRegDeleteValue_rep_coder, sizeof(struct winreg_BaseRegDeleteValue_rep),
        },
        {WINREG_BASEREGENUMKEY, "BaseRegEnumKey",
         winreg_BaseRegEnumKey_req_coder, sizeof(struct winreg_BaseRegEnumKey_req),
         winreg_BaseRegEnumKey_rep_coder, sizeof(struct winreg_BaseRegEnumKey_rep),
        },
        {WINREG_BASEREGENUMVALUE, "BaseRegEnumValue",
         winreg_BaseRegEnumValue_req_coder, sizeof(struct winreg_BaseRegEnumValue_req),
         winreg_BaseRegEnumValue_rep_coder, sizeof(struct winreg_BaseRegEnumValue_rep),
        },
        {WINREG_BASEREGOPENKEY, "BaseRegOpenKey",
         winreg_BaseRegOpenKey_req_coder, sizeof(struct winreg_BaseRegOpenKey_req),
         winreg_BaseRegOpenKey_rep_coder, sizeof(struct winreg_BaseRegOpenKey_rep),
        },
        {WINREG_BASEREGQUERYINFOKEY, "BaseRegQueryInfoKey",
         winreg_BaseRegQueryInfoKey_req_coder, sizeof(struct winreg_BaseRegQueryInfoKey_req),
         winreg_BaseRegQueryInfoKey_rep_coder, sizeof(struct winreg_BaseRegQueryInfoKey_rep),
        },
        {WINREG_BASEREGSETVALUE, "BaseRegSetValue",
         winreg_BaseRegSetValue_req_coder, sizeof(struct winreg_BaseRegSetValue_req),
         winreg_BaseRegSetValue_rep_coder, sizeof(struct winreg_BaseRegSetValue_rep),
        },
        {WINREG_OPENCURRENTCONFIG, "OpenCurrentConfig",
         winreg_OpenCurrentConfig_req_coder, sizeof(struct winreg_OpenCurrentConfig_req),
         winreg_OpenCurrentConfig_rep_coder, sizeof(struct winreg_OpenCurrentConfig_rep),
        },
        {-1, NULL, NULL, 0, NULL, 0}
};
