/* -*-  mode:c; tab-width:8; c-basic-offset:8; indent-tabs-mode:nil;  -*- */
/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * AUTO-GENERATED by idlcomp.py from lsa.idl — do not edit.
 */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif

#ifdef HAVE_STDINT_H
#include <stdint.h>
#endif

#ifdef HAVE_STDLIB_H
#include <stdlib.h>
#endif

#ifdef HAVE_STRING_H
#include <string.h>
#endif

#ifdef STDC_HEADERS
#include <stddef.h>
#endif

#ifdef HAVE_SYS_TYPES_H
#include <sys/types.h>
#endif

#ifdef HAVE_SYS_STAT_H
#include <sys/stat.h>
#endif

#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif

#ifdef HAVE_SYS_UNISTD_H
#include <sys/unistd.h>
#endif

#include <errno.h>
#include <stdio.h>


#include <smb2/smb2.h>
#include <smb2/libsmb2.h>
#include <dcerpc/dcerpc.h>
#include <dcerpc/dcerpc-dtyp.h>
#include <dcerpc/dcerpc-lsa.h>
#include <smb2/libsmb2-raw.h>
#include "dcerpc-private.h"

#define LSA_UUID    0x12345778, 0x1234, 0xabcd, {0xef, 0x00, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab}

p_syntax_id_t lsa_interface = {
        {LSA_UUID}, 0, 0
};

static int lsa_uint8_t_ptr_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
static int lsa_STRING_ptr_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
static int lsa_LSAPR_SECURITY_DESCRIPTOR_ptr_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
static int lsa_SECURITY_QUALITY_OF_SERVICE_ptr_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
static int lsa_RPC_SID_ptr_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
static int lsa_RPC_SID_pelem_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_LSAPR_TRUST_INFORMATION_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_LSAPR_TRANSLATED_NAME_EX_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_LSAPR_TRANSLATED_SID_EX_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

static int
lsa_RPC_SID_ptr_carray_coder(char *name, struct dcerpc_context *dce,
                     struct dcerpc_pdu *pdu,
                     struct dcerpc_iovec *iov, int *offset,
                     void *ptr)
{
        return dcerpc_scalar_carray_coder(name, dce, pdu, iov, offset,
                                   dcerpc_get_size_is(pdu), ptr,
                                   sizeof(RPC_SID *),
                                   lsa_RPC_SID_pelem_coder);
}

static int
lsa_LSAPR_TRUST_INFORMATION_carray_coder(char *name, struct dcerpc_context *dce,
                     struct dcerpc_pdu *pdu,
                     struct dcerpc_iovec *iov, int *offset,
                     void *ptr)
{
        return dcerpc_carray_coder(name, dce, pdu, iov, offset,
                                   dcerpc_get_size_is(pdu), ptr,
                                   sizeof(struct lsa_LSAPR_TRUST_INFORMATION),
                                   lsa_LSAPR_TRUST_INFORMATION_coder);
}

static int
lsa_LSAPR_TRANSLATED_NAME_EX_carray_coder(char *name, struct dcerpc_context *dce,
                     struct dcerpc_pdu *pdu,
                     struct dcerpc_iovec *iov, int *offset,
                     void *ptr)
{
        return dcerpc_carray_coder(name, dce, pdu, iov, offset,
                                   dcerpc_get_size_is(pdu), ptr,
                                   sizeof(struct lsa_LSAPR_TRANSLATED_NAME_EX),
                                   lsa_LSAPR_TRANSLATED_NAME_EX_coder);
}

static int
lsa_LSAPR_TRANSLATED_SID_EX_carray_coder(char *name, struct dcerpc_context *dce,
                     struct dcerpc_pdu *pdu,
                     struct dcerpc_iovec *iov, int *offset,
                     void *ptr)
{
        return dcerpc_carray_coder(name, dce, pdu, iov, offset,
                                   dcerpc_get_size_is(pdu), ptr,
                                   sizeof(struct lsa_LSAPR_TRANSLATED_SID_EX),
                                   lsa_LSAPR_TRANSLATED_SID_EX_coder);
}

static int
lsa_RPC_UNICODE_STRING_carray_coder(char *name, struct dcerpc_context *dce,
                     struct dcerpc_pdu *pdu,
                     struct dcerpc_iovec *iov, int *offset,
                     void *ptr)
{
        return dcerpc_scalar_carray_coder(name, dce, pdu, iov, offset,
                                   dcerpc_get_size_is(pdu), ptr,
                                   sizeof(char *),
                                   dcerpc_RPC_UNICODE_STRING_coder);
}

static int
lsa_uint8_t_ptr_coder(char *name, struct dcerpc_context *dce,
                     struct dcerpc_pdu *pdu,
                     struct dcerpc_iovec *iov, int *offset,
                     void *ptr)
{
        uint8_t **pp = ptr;

        if (dcerpc_pdu_direction(pdu) == DCERPC_DECODE && *pp == NULL) {
                *pp = dcerpc_alloc_data(pdu, sizeof(**pp));
                if (*pp == NULL) {
                        return -1;
                }
        }
        return dcerpc_uint8_coder(name, dce, pdu, iov, offset, *pp);
}

static int
lsa_STRING_ptr_coder(char *name, struct dcerpc_context *dce,
                     struct dcerpc_pdu *pdu,
                     struct dcerpc_iovec *iov, int *offset,
                     void *ptr)
{
        struct lsa_STRING **pp = ptr;

        if (dcerpc_pdu_direction(pdu) == DCERPC_DECODE && *pp == NULL) {
                *pp = dcerpc_alloc_data(pdu, sizeof(**pp));
                if (*pp == NULL) {
                        return -1;
                }
        }
        return lsa_STRING_struct_coder(name, dce, pdu, iov, offset, *pp);
}

static int
lsa_LSAPR_SECURITY_DESCRIPTOR_ptr_coder(char *name, struct dcerpc_context *dce,
                     struct dcerpc_pdu *pdu,
                     struct dcerpc_iovec *iov, int *offset,
                     void *ptr)
{
        struct lsa_LSAPR_SECURITY_DESCRIPTOR **pp = ptr;

        if (dcerpc_pdu_direction(pdu) == DCERPC_DECODE && *pp == NULL) {
                *pp = dcerpc_alloc_data(pdu, sizeof(**pp));
                if (*pp == NULL) {
                        return -1;
                }
        }
        return lsa_LSAPR_SECURITY_DESCRIPTOR_struct_coder(name, dce, pdu, iov, offset, *pp);
}

static int
lsa_SECURITY_QUALITY_OF_SERVICE_ptr_coder(char *name, struct dcerpc_context *dce,
                     struct dcerpc_pdu *pdu,
                     struct dcerpc_iovec *iov, int *offset,
                     void *ptr)
{
        struct lsa_SECURITY_QUALITY_OF_SERVICE **pp = ptr;

        if (dcerpc_pdu_direction(pdu) == DCERPC_DECODE && *pp == NULL) {
                *pp = dcerpc_alloc_data(pdu, sizeof(**pp));
                if (*pp == NULL) {
                        return -1;
                }
        }
        return lsa_SECURITY_QUALITY_OF_SERVICE_struct_coder(name, dce, pdu, iov, offset, *pp);
}

static int
lsa_RPC_SID_ptr_coder(char *name, struct dcerpc_context *dce,
                     struct dcerpc_pdu *pdu,
                     struct dcerpc_iovec *iov, int *offset,
                     void *ptr)
{
        RPC_SID **pp = ptr;

        if (dcerpc_pdu_direction(pdu) == DCERPC_DECODE && *pp == NULL) {
                *pp = dcerpc_alloc_data(pdu, sizeof(**pp));
                if (*pp == NULL) {
                        return -1;
                }
        }
        return dcerpc_sid_coder(name, dce, pdu, iov, offset, *pp);
}

static int
lsa_RPC_SID_pelem_coder(char *name, struct dcerpc_context *dce,
                     struct dcerpc_pdu *pdu,
                     struct dcerpc_iovec *iov, int *offset,
                     void *ptr)
{
        RPC_SID **pp = ptr;

        return dcerpc_ptr_coder(name, dce, pdu, iov, offset,
                                (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE &&
                                 *pp == NULL) ? NULL : (void *)pp,
                                PTR_UNIQUE, lsa_RPC_SID_ptr_coder);
}

static int
lsa_LSAPR_HANDLE_param_coder(char *name, struct dcerpc_context *dce,
                     struct dcerpc_pdu *pdu,
                     struct dcerpc_iovec *iov, int *offset,
                     void *ptr)
{
        return dcerpc_struct_coder(name, dce, pdu, iov, offset, ptr,
                                   dcerpc_context_handle_coder);
}

/* POLICY_ACCESS_MASK: NDR uint32; YAML/JSON show the flag names */
static struct dcerpc_uint32_pretty_printer lsa_POLICY_ACCESS_MASK_pp = {
        .fmt = "0x%08x",
        .bitfields = {
                { "POLICY_VIEW_LOCAL_INFORMATION", LSA_POLICY_VIEW_LOCAL_INFORMATION, LSA_POLICY_VIEW_LOCAL_INFORMATION },
                { "POLICY_VIEW_AUDIT_INFORMATION", LSA_POLICY_VIEW_AUDIT_INFORMATION, LSA_POLICY_VIEW_AUDIT_INFORMATION },
                { "POLICY_GET_PRIVATE_INFORMATION", LSA_POLICY_GET_PRIVATE_INFORMATION, LSA_POLICY_GET_PRIVATE_INFORMATION },
                { "POLICY_TRUST_ADMIN", LSA_POLICY_TRUST_ADMIN, LSA_POLICY_TRUST_ADMIN },
                { "POLICY_CREATE_ACCOUNT", LSA_POLICY_CREATE_ACCOUNT, LSA_POLICY_CREATE_ACCOUNT },
                { "POLICY_CREATE_SECRET", LSA_POLICY_CREATE_SECRET, LSA_POLICY_CREATE_SECRET },
                { "POLICY_CREATE_PRIVILEGE", LSA_POLICY_CREATE_PRIVILEGE, LSA_POLICY_CREATE_PRIVILEGE },
                { "POLICY_SET_DEFAULT_QUOTA_LIMITS", LSA_POLICY_SET_DEFAULT_QUOTA_LIMITS, LSA_POLICY_SET_DEFAULT_QUOTA_LIMITS },
                { "POLICY_SET_AUDIT_REQUIREMENTS", LSA_POLICY_SET_AUDIT_REQUIREMENTS, LSA_POLICY_SET_AUDIT_REQUIREMENTS },
                { "POLICY_AUDIT_LOG_ADMIN", LSA_POLICY_AUDIT_LOG_ADMIN, LSA_POLICY_AUDIT_LOG_ADMIN },
                { "POLICY_SERVER_ADMIN", LSA_POLICY_SERVER_ADMIN, LSA_POLICY_SERVER_ADMIN },
                { "POLICY_LOOKUP_NAMES", LSA_POLICY_LOOKUP_NAMES, LSA_POLICY_LOOKUP_NAMES },
                { "POLICY_NOTIFICATION", LSA_POLICY_NOTIFICATION, LSA_POLICY_NOTIFICATION },
                { NULL, 0, 0 },
        },
};

int
lsa_POLICY_ACCESS_MASK_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_uint32_coder_pp(name, dce, pdu, iov, offset, ptr,
                                      &lsa_POLICY_ACCESS_MASK_pp);
}

/* SID_NAME_USE: NDR uint32; YAML/JSON show the value names */
static struct dcerpc_uint32_pretty_printer lsa_SID_NAME_USE_pp = {
        .fmt = "%u",
        .bitfields = {
                { "SidTypeUser", 0xffffffff, LSA_SidTypeUser },
                { "SidTypeGroup", 0xffffffff, LSA_SidTypeGroup },
                { "SidTypeDomain", 0xffffffff, LSA_SidTypeDomain },
                { "SidTypeAlias", 0xffffffff, LSA_SidTypeAlias },
                { "SidTypeWellKnownGroup", 0xffffffff, LSA_SidTypeWellKnownGroup },
                { "SidTypeDeletedAccount", 0xffffffff, LSA_SidTypeDeletedAccount },
                { "SidTypeInvalid", 0xffffffff, LSA_SidTypeInvalid },
                { "SidTypeUnknown", 0xffffffff, LSA_SidTypeUnknown },
                { "SidTypeComputer", 0xffffffff, LSA_SidTypeComputer },
                { "SidTypeLabel", 0xffffffff, LSA_SidTypeLabel },
                { "SidTypeLogonSession", 0xffffffff, LSA_SidTypeLogonSession },
                { NULL, 0, 0 },
        },
};

int
lsa_SID_NAME_USE_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_uint32_coder_pp(name, dce, pdu, iov, offset, ptr,
                                      &lsa_SID_NAME_USE_pp);
}

/* LSAP_LOOKUP_LEVEL: NDR uint32; YAML/JSON show the value names */
static struct dcerpc_uint32_pretty_printer lsa_LSAP_LOOKUP_LEVEL_pp = {
        .fmt = "%u",
        .bitfields = {
                { "LsapLookupWksta", 0xffffffff, LSA_LsapLookupWksta },
                { "LsapLookupPDC", 0xffffffff, LSA_LsapLookupPDC },
                { "LsapLookupTDL", 0xffffffff, LSA_LsapLookupTDL },
                { "LsapLookupGC", 0xffffffff, LSA_LsapLookupGC },
                { "LsapLookupXForestReferral", 0xffffffff, LSA_LsapLookupXForestReferral },
                { "LsapLookupXForestResolve", 0xffffffff, LSA_LsapLookupXForestResolve },
                { "LsapLookupRODCReferralToFullDC", 0xffffffff, LSA_LsapLookupRODCReferralToFullDC },
                { NULL, 0, 0 },
        },
};

int
lsa_LSAP_LOOKUP_LEVEL_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_uint32_coder_pp(name, dce, pdu, iov, offset, ptr,
                                      &lsa_LSAP_LOOKUP_LEVEL_pp);
}

int
lsa_STRING_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_STRING *s = ptr;

        (void)name;
        if (dcerpc_uint16_coder("Length", dce, pdu, iov, offset, &s->Length)) {
                return -1;
        }
        if (dcerpc_uint16_coder("MaximumLength", dce, pdu, iov, offset, &s->MaximumLength)) {
                return -1;
        }
        if (dcerpc_ptr_coder("Buffer", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE &&
                              s->Buffer.data == NULL) ? NULL : &s->Buffer,
                             PTR_UNIQUE, dcerpc_varying_bytes_coder)) {
                return -1;
        }

        return 0;
}

int
lsa_STRING_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_struct_coder(name, dce, pdu, iov, offset, ptr,
                                   lsa_STRING_coder);
}

int
lsa_LSAPR_SECURITY_DESCRIPTOR_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_LSAPR_SECURITY_DESCRIPTOR *s = ptr;

        (void)name;
        if (dcerpc_blob_len_coder("Length", dce, pdu, iov, offset,
                                  &s->Length, s->SecurityDescriptor,
                                  dcerpc_SECURITY_DESCRIPTOR_coder)) {
                return -1;
        }
        if (dcerpc_blob_coder("SecurityDescriptor", dce, pdu, iov, offset,
                              s->Length, &s->SecurityDescriptor,
                              sizeof(SECURITY_DESCRIPTOR),
                              dcerpc_SECURITY_DESCRIPTOR_coder)) {
                return -1;
        }

        return 0;
}

int
lsa_LSAPR_SECURITY_DESCRIPTOR_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_struct_coder(name, dce, pdu, iov, offset, ptr,
                                   lsa_LSAPR_SECURITY_DESCRIPTOR_coder);
}

/* enum SECURITY_IMPERSONATION_LEVEL: NDR uint16 (default, not [v1_enum]); named YAML values */
static struct dcerpc_uint32_pretty_printer lsa_SECURITY_IMPERSONATION_LEVEL_pp = {
        .fmt = "%u",
        .bitfields = {
                { "SecurityAnonymous", 0xffff, (uint16_t)LSA_SecurityAnonymous },
                { "SecurityIdentification", 0xffff, (uint16_t)LSA_SecurityIdentification },
                { "SecurityImpersonation", 0xffff, (uint16_t)LSA_SecurityImpersonation },
                { "SecurityDelegation", 0xffff, (uint16_t)LSA_SecurityDelegation },
                { NULL, 0, 0 },
        },
};

int
lsa_SECURITY_IMPERSONATION_LEVEL_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        enum lsa_SECURITY_IMPERSONATION_LEVEL *e = ptr;
        uint16_t tmp = 0;

        if (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE) {
                tmp = (uint16_t)*e;
        }
        if (dcerpc_uint16_coder_pp(name, dce, pdu, iov, offset, &tmp,
                                   &lsa_SECURITY_IMPERSONATION_LEVEL_pp)) {
                return -1;
        }
        if (dcerpc_pdu_direction(pdu) == DCERPC_DECODE) {
                *e = (enum lsa_SECURITY_IMPERSONATION_LEVEL)tmp;
        }
        return 0;
}

int
lsa_SECURITY_QUALITY_OF_SERVICE_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_SECURITY_QUALITY_OF_SERVICE *s = ptr;

        (void)name;
        if (dcerpc_uint32_coder("Length", dce, pdu, iov, offset, &s->Length)) {
                return -1;
        }
        if (lsa_SECURITY_IMPERSONATION_LEVEL_coder("ImpersonationLevel", dce, pdu, iov, offset, &s->ImpersonationLevel)) {
                return -1;
        }
        if (dcerpc_uint8_coder("ContextTrackingMode", dce, pdu, iov, offset, &s->ContextTrackingMode)) {
                return -1;
        }
        if (dcerpc_uint8_coder("EffectiveOnly", dce, pdu, iov, offset, &s->EffectiveOnly)) {
                return -1;
        }

        return 0;
}

int
lsa_SECURITY_QUALITY_OF_SERVICE_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_struct_coder(name, dce, pdu, iov, offset, ptr,
                                   lsa_SECURITY_QUALITY_OF_SERVICE_coder);
}

int
lsa_LSAPR_OBJECT_ATTRIBUTES_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_LSAPR_OBJECT_ATTRIBUTES *s = ptr;

        (void)name;
        if (dcerpc_uint32_coder("Length", dce, pdu, iov, offset, &s->Length)) {
                return -1;
        }
        if (dcerpc_ptr_coder("RootDirectory", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE &&
                              s->RootDirectory == NULL) ? NULL : &s->RootDirectory,
                             PTR_UNIQUE, lsa_uint8_t_ptr_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("ObjectName", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE &&
                              s->ObjectName == NULL) ? NULL : &s->ObjectName,
                             PTR_UNIQUE, lsa_STRING_ptr_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Attributes", dce, pdu, iov, offset, &s->Attributes)) {
                return -1;
        }
        if (dcerpc_ptr_coder("SecurityDescriptor", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE &&
                              s->SecurityDescriptor == NULL) ? NULL : &s->SecurityDescriptor,
                             PTR_UNIQUE, lsa_LSAPR_SECURITY_DESCRIPTOR_ptr_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("SecurityQualityOfService", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE &&
                              s->SecurityQualityOfService == NULL) ? NULL : &s->SecurityQualityOfService,
                             PTR_UNIQUE, lsa_SECURITY_QUALITY_OF_SERVICE_ptr_coder)) {
                return -1;
        }

        return 0;
}

int
lsa_LSAPR_OBJECT_ATTRIBUTES_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_struct_coder(name, dce, pdu, iov, offset, ptr,
                                   lsa_LSAPR_OBJECT_ATTRIBUTES_coder);
}

int
lsa_LSAPR_SID_ENUM_BUFFER_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_LSAPR_SID_ENUM_BUFFER *s = ptr;

        (void)name;
        if (dcerpc_uint32_coder("Entries", dce, pdu, iov, offset, &s->Entries)) {
                return -1;
        }
        dcerpc_set_size_is(pdu, s->Entries);
        if (dcerpc_pdu_direction(pdu) == DCERPC_DECODE && s->Entries) {
                if (s->SidInfo == NULL) {
                        size_t esize = sizeof(RPC_SID *);
                        if (s->Entries > SIZE_MAX / esize) {
                                return -1;
                        }
                        s->SidInfo = dcerpc_alloc_data(pdu,
                                (size_t)s->Entries * esize);
                        if (s->SidInfo == NULL) {
                                return -1;
                        }
                }
        }
        if (dcerpc_ptr_coder("SidInfo", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_DECODE &&
                              s->SidInfo == NULL) ? (void *)&s->SidInfo : (void *)s->SidInfo,
                             PTR_UNIQUE, lsa_RPC_SID_ptr_carray_coder)) {
                return -1;
        }

        return 0;
}

int
lsa_LSAPR_SID_ENUM_BUFFER_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_struct_coder(name, dce, pdu, iov, offset, ptr,
                                   lsa_LSAPR_SID_ENUM_BUFFER_coder);
}

int
lsa_LSAPR_TRUST_INFORMATION_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_LSAPR_TRUST_INFORMATION *s = ptr;

        (void)name;
        if (dcerpc_RPC_UNICODE_STRING_coder("Name", dce, pdu, iov, offset, &s->Name)) {
                return -1;
        }
        if (dcerpc_ptr_coder("Sid", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE &&
                              s->Sid == NULL) ? NULL : &s->Sid,
                             PTR_UNIQUE, lsa_RPC_SID_ptr_coder)) {
                return -1;
        }

        return 0;
}

int
lsa_LSAPR_TRUST_INFORMATION_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_struct_coder(name, dce, pdu, iov, offset, ptr,
                                   lsa_LSAPR_TRUST_INFORMATION_coder);
}

int
lsa_LSAPR_REFERENCED_DOMAIN_LIST_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_LSAPR_REFERENCED_DOMAIN_LIST *s = ptr;

        (void)name;
        if (dcerpc_uint32_coder("Entries", dce, pdu, iov, offset, &s->Entries)) {
                return -1;
        }
        dcerpc_set_size_is(pdu, s->Entries);
        if (dcerpc_pdu_direction(pdu) == DCERPC_DECODE && s->Entries) {
                if (s->Domains == NULL) {
                        size_t esize = sizeof(struct lsa_LSAPR_TRUST_INFORMATION);
                        if (s->Entries > SIZE_MAX / esize) {
                                return -1;
                        }
                        s->Domains = dcerpc_alloc_data(pdu,
                                (size_t)s->Entries * esize);
                        if (s->Domains == NULL) {
                                return -1;
                        }
                }
        }
        if (dcerpc_ptr_coder("Domains", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_DECODE &&
                              s->Domains == NULL) ? (void *)&s->Domains : (void *)s->Domains,
                             PTR_UNIQUE, lsa_LSAPR_TRUST_INFORMATION_carray_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("MaxEntries", dce, pdu, iov, offset, &s->MaxEntries)) {
                return -1;
        }

        return 0;
}

int
lsa_LSAPR_REFERENCED_DOMAIN_LIST_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_struct_coder(name, dce, pdu, iov, offset, ptr,
                                   lsa_LSAPR_REFERENCED_DOMAIN_LIST_coder);
}

int
lsa_LSAPR_TRANSLATED_NAME_EX_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_LSAPR_TRANSLATED_NAME_EX *s = ptr;

        (void)name;
        if (lsa_SID_NAME_USE_coder("Use", dce, pdu, iov, offset, &s->Use)) {
                return -1;
        }
        if (dcerpc_RPC_UNICODE_STRING_coder("Name", dce, pdu, iov, offset, &s->Name)) {
                return -1;
        }
        if (dcerpc_uint32_coder("DomainIndex", dce, pdu, iov, offset, &s->DomainIndex)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Flags", dce, pdu, iov, offset, &s->Flags)) {
                return -1;
        }

        return 0;
}

int
lsa_LSAPR_TRANSLATED_NAME_EX_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_struct_coder(name, dce, pdu, iov, offset, ptr,
                                   lsa_LSAPR_TRANSLATED_NAME_EX_coder);
}

int
lsa_LSAPR_TRANSLATED_NAMES_EX_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_LSAPR_TRANSLATED_NAMES_EX *s = ptr;

        (void)name;
        if (dcerpc_uint32_coder("Entries", dce, pdu, iov, offset, &s->Entries)) {
                return -1;
        }
        dcerpc_set_size_is(pdu, s->Entries);
        if (dcerpc_pdu_direction(pdu) == DCERPC_DECODE && s->Entries) {
                if (s->Names == NULL) {
                        size_t esize = sizeof(struct lsa_LSAPR_TRANSLATED_NAME_EX);
                        if (s->Entries > SIZE_MAX / esize) {
                                return -1;
                        }
                        s->Names = dcerpc_alloc_data(pdu,
                                (size_t)s->Entries * esize);
                        if (s->Names == NULL) {
                                return -1;
                        }
                }
        }
        if (dcerpc_ptr_coder("Names", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_DECODE &&
                              s->Names == NULL) ? (void *)&s->Names : (void *)s->Names,
                             PTR_UNIQUE, lsa_LSAPR_TRANSLATED_NAME_EX_carray_coder)) {
                return -1;
        }

        return 0;
}

int
lsa_LSAPR_TRANSLATED_NAMES_EX_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_struct_coder(name, dce, pdu, iov, offset, ptr,
                                   lsa_LSAPR_TRANSLATED_NAMES_EX_coder);
}

int
lsa_LSAPR_TRANSLATED_SID_EX_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_LSAPR_TRANSLATED_SID_EX *s = ptr;

        (void)name;
        if (lsa_SID_NAME_USE_coder("Use", dce, pdu, iov, offset, &s->Use)) {
                return -1;
        }
        if (dcerpc_uint32_coder("RelativeId", dce, pdu, iov, offset, &s->RelativeId)) {
                return -1;
        }
        if (dcerpc_uint32_coder("DomainIndex", dce, pdu, iov, offset, &s->DomainIndex)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Flags", dce, pdu, iov, offset, &s->Flags)) {
                return -1;
        }

        return 0;
}

int
lsa_LSAPR_TRANSLATED_SID_EX_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_struct_coder(name, dce, pdu, iov, offset, ptr,
                                   lsa_LSAPR_TRANSLATED_SID_EX_coder);
}

int
lsa_LSAPR_TRANSLATED_SIDS_EX_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_LSAPR_TRANSLATED_SIDS_EX *s = ptr;

        (void)name;
        if (dcerpc_uint32_coder("Entries", dce, pdu, iov, offset, &s->Entries)) {
                return -1;
        }
        dcerpc_set_size_is(pdu, s->Entries);
        if (dcerpc_pdu_direction(pdu) == DCERPC_DECODE && s->Entries) {
                if (s->Sids == NULL) {
                        size_t esize = sizeof(struct lsa_LSAPR_TRANSLATED_SID_EX);
                        if (s->Entries > SIZE_MAX / esize) {
                                return -1;
                        }
                        s->Sids = dcerpc_alloc_data(pdu,
                                (size_t)s->Entries * esize);
                        if (s->Sids == NULL) {
                                return -1;
                        }
                }
        }
        if (dcerpc_ptr_coder("Sids", dce, pdu, iov, offset,
                             (dcerpc_pdu_direction(pdu) == DCERPC_DECODE &&
                              s->Sids == NULL) ? (void *)&s->Sids : (void *)s->Sids,
                             PTR_UNIQUE, lsa_LSAPR_TRANSLATED_SID_EX_carray_coder)) {
                return -1;
        }

        return 0;
}

int
lsa_LSAPR_TRANSLATED_SIDS_EX_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        return dcerpc_struct_coder(name, dce, pdu, iov, offset, ptr,
                                   lsa_LSAPR_TRANSLATED_SIDS_EX_coder);
}

/*****************
 * Function: 0x00  Close  (LSA_CLOSE)
 *****************/
int
lsa_Close_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_Close_req *req = ptr;

        (void)name;
        if (dcerpc_ptr_coder("PolicyHandle", dce, pdu, iov, offset, &req->PolicyHandle,
                             PTR_REF, lsa_LSAPR_HANDLE_param_coder)) {
                return -1;
        }

        return 0;
}

int
lsa_Close_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_Close_rep *rep = ptr;

        (void)name;
        if (dcerpc_ptr_coder("PolicyHandle", dce, pdu, iov, offset, &rep->PolicyHandle,
                             PTR_REF, lsa_LSAPR_HANDLE_param_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/*****************
 * Function: 0x2c  OpenPolicy2  (LSA_OPENPOLICY2)
 *****************/
int
lsa_OpenPolicy2_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_OpenPolicy2_req *req = ptr;

        (void)name;
        if (dcerpc_pdu_direction(pdu) == DCERPC_ENCODE &&
            req->SystemName == NULL) {
                if (dcerpc_ptr_coder("SystemName", dce, pdu, iov, offset, NULL,
                                     PTR_UNIQUE, dcerpc_utf16z_coder)) {
                        return -1;
                }
        } else if (dcerpc_ptr_coder("SystemName", dce, pdu, iov, offset, &req->SystemName,
                                    PTR_UNIQUE, dcerpc_utf16z_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("ObjectAttributes", dce, pdu, iov, offset, &req->ObjectAttributes,
                             PTR_REF, lsa_LSAPR_OBJECT_ATTRIBUTES_struct_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("DesiredAccess", dce, pdu, iov, offset, &req->DesiredAccess,
                             PTR_REF, lsa_POLICY_ACCESS_MASK_coder)) {
                return -1;
        }

        return 0;
}

int
lsa_OpenPolicy2_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_OpenPolicy2_rep *rep = ptr;

        (void)name;
        if (dcerpc_ptr_coder("PolicyHandle", dce, pdu, iov, offset, &rep->PolicyHandle,
                             PTR_REF, lsa_LSAPR_HANDLE_param_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/*****************
 * Function: 0x39  LookupSids2  (LSA_LOOKUPSIDS2)
 *****************/
int
lsa_LookupSids2_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_LookupSids2_req *req = ptr;

        (void)name;
        if (dcerpc_ptr_coder("PolicyHandle", dce, pdu, iov, offset, &req->PolicyHandle,
                             PTR_REF, lsa_LSAPR_HANDLE_param_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("SidEnumBuffer", dce, pdu, iov, offset, &req->SidEnumBuffer,
                             PTR_REF, lsa_LSAPR_SID_ENUM_BUFFER_struct_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("TranslatedNames", dce, pdu, iov, offset, &req->TranslatedNames,
                             PTR_REF, lsa_LSAPR_TRANSLATED_NAMES_EX_struct_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("LookupLevel", dce, pdu, iov, offset, &req->LookupLevel,
                             PTR_REF, lsa_LSAP_LOOKUP_LEVEL_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("MappedCount", dce, pdu, iov, offset, &req->MappedCount,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("LookupOptions", dce, pdu, iov, offset, &req->LookupOptions,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("ClientRevision", dce, pdu, iov, offset, &req->ClientRevision,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }

        return 0;
}

int
lsa_LookupSids2_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_LookupSids2_rep *rep = ptr;

        (void)name;
        if (dcerpc_ptr_coder("ReferencedDomains", dce, pdu, iov, offset, &rep->ReferencedDomains,
                             PTR_UNIQUE, lsa_LSAPR_REFERENCED_DOMAIN_LIST_struct_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("TranslatedNames", dce, pdu, iov, offset, &rep->TranslatedNames,
                             PTR_REF, lsa_LSAPR_TRANSLATED_NAMES_EX_struct_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("MappedCount", dce, pdu, iov, offset, &rep->MappedCount,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/*****************
 * Function: 0x3a  LookupNames2  (LSA_LOOKUPNAMES2)
 *****************/
int
lsa_LookupNames2_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_LookupNames2_req *req = ptr;

        (void)name;
        if (dcerpc_ptr_coder("PolicyHandle", dce, pdu, iov, offset, &req->PolicyHandle,
                             PTR_REF, lsa_LSAPR_HANDLE_param_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("Count", dce, pdu, iov, offset, &req->Count,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }
        dcerpc_set_size_is(pdu, req->Count);
        if (dcerpc_pdu_direction(pdu) == DCERPC_DECODE && req->Count &&
            req->Names == NULL) {
                if (req->Count > SIZE_MAX / sizeof(char *)) {
                        return -1;
                }
                req->Names = dcerpc_alloc_data(pdu,
                        (size_t)req->Count * sizeof(char *));
                if (req->Names == NULL) {
                        return -1;
                }
        }
        if (dcerpc_ptr_coder("Names", dce, pdu, iov, offset,
                             req->Names ? (void *)req->Names : (void *)&req->Names,
                             PTR_REF, lsa_RPC_UNICODE_STRING_carray_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("TranslatedSids", dce, pdu, iov, offset, &req->TranslatedSids,
                             PTR_REF, lsa_LSAPR_TRANSLATED_SIDS_EX_struct_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("LookupLevel", dce, pdu, iov, offset, &req->LookupLevel,
                             PTR_REF, lsa_LSAP_LOOKUP_LEVEL_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("MappedCount", dce, pdu, iov, offset, &req->MappedCount,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("LookupOptions", dce, pdu, iov, offset, &req->LookupOptions,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("ClientRevision", dce, pdu, iov, offset, &req->ClientRevision,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }

        return 0;
}

int
lsa_LookupNames2_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu,
                struct dcerpc_iovec *iov, int *offset,
                void *ptr)
{
        struct lsa_LookupNames2_rep *rep = ptr;

        (void)name;
        if (dcerpc_ptr_coder("ReferencedDomains", dce, pdu, iov, offset, &rep->ReferencedDomains,
                             PTR_UNIQUE, lsa_LSAPR_REFERENCED_DOMAIN_LIST_struct_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("TranslatedSids", dce, pdu, iov, offset, &rep->TranslatedSids,
                             PTR_REF, lsa_LSAPR_TRANSLATED_SIDS_EX_struct_coder)) {
                return -1;
        }
        if (dcerpc_ptr_coder("MappedCount", dce, pdu, iov, offset, &rep->MappedCount,
                             PTR_REF, dcerpc_uint32_coder)) {
                return -1;
        }
        if (dcerpc_uint32_coder("Status", dce, pdu, iov, offset, &rep->status)) {
                return -1;
        }

        return 0;
}

/* Procedure table: opnum → request/response coders and sizes */
struct dcerpc_procedure lsa_procs[] = {
        {LSA_CLOSE, "Close",
         lsa_Close_req_coder, sizeof(struct lsa_Close_req),
         lsa_Close_rep_coder, sizeof(struct lsa_Close_rep),
        },
        {LSA_OPENPOLICY2, "OpenPolicy2",
         lsa_OpenPolicy2_req_coder, sizeof(struct lsa_OpenPolicy2_req),
         lsa_OpenPolicy2_rep_coder, sizeof(struct lsa_OpenPolicy2_rep),
        },
        {LSA_LOOKUPSIDS2, "LookupSids2",
         lsa_LookupSids2_req_coder, sizeof(struct lsa_LookupSids2_req),
         lsa_LookupSids2_rep_coder, sizeof(struct lsa_LookupSids2_rep),
        },
        {LSA_LOOKUPNAMES2, "LookupNames2",
         lsa_LookupNames2_req_coder, sizeof(struct lsa_LookupNames2_req),
         lsa_LookupNames2_rep_coder, sizeof(struct lsa_LookupNames2_rep),
        },
        {-1, NULL, NULL, 0, NULL, 0}
};
