/* -*-  mode:c; tab-width:8; c-basic-offset:8; indent-tabs-mode:nil;  -*- */
/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * AUTO-GENERATED by idlcomp.py from lsa.idl — do not edit.
 *
 * Types and coders are derived from the IDL; field names follow the IDL.
 */
#ifndef _DCERPC_LSA_H_
#define _DCERPC_LSA_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include <stdint.h>

#include <dcerpc/dcerpc.h>
#include <dcerpc/dcerpc-dtyp.h>

/* POLICY_ACCESS_MASK: bitmap, stored as uint32_t */
#define LSA_POLICY_VIEW_LOCAL_INFORMATION   0x00000001
#define LSA_POLICY_VIEW_AUDIT_INFORMATION   0x00000002
#define LSA_POLICY_GET_PRIVATE_INFORMATION  0x00000004
#define LSA_POLICY_TRUST_ADMIN              0x00000008
#define LSA_POLICY_CREATE_ACCOUNT           0x00000010
#define LSA_POLICY_CREATE_SECRET            0x00000020
#define LSA_POLICY_CREATE_PRIVILEGE         0x00000040
#define LSA_POLICY_SET_DEFAULT_QUOTA_LIMITS 0x00000080
#define LSA_POLICY_SET_AUDIT_REQUIREMENTS   0x00000100
#define LSA_POLICY_AUDIT_LOG_ADMIN          0x00000200
#define LSA_POLICY_SERVER_ADMIN             0x00000400
#define LSA_POLICY_LOOKUP_NAMES             0x00000800
#define LSA_POLICY_NOTIFICATION             0x00001000

/* SID_NAME_USE: stored as uint32_t */
enum lsa_SID_NAME_USE {
        LSA_SidTypeUser = 1,
        LSA_SidTypeGroup = 2,
        LSA_SidTypeDomain = 3,
        LSA_SidTypeAlias = 4,
        LSA_SidTypeWellKnownGroup = 5,
        LSA_SidTypeDeletedAccount = 6,
        LSA_SidTypeInvalid = 7,
        LSA_SidTypeUnknown = 8,
        LSA_SidTypeComputer = 9,
        LSA_SidTypeLabel = 10,
        LSA_SidTypeLogonSession = 11
};

/* LSAP_LOOKUP_LEVEL: stored as uint32_t */
enum lsa_LSAP_LOOKUP_LEVEL {
        LSA_LsapLookupWksta = 1,
        LSA_LsapLookupPDC = 2,
        LSA_LsapLookupTDL = 3,
        LSA_LsapLookupGC = 4,
        LSA_LsapLookupXForestReferral = 5,
        LSA_LsapLookupXForestResolve = 6,
        LSA_LsapLookupRODCReferralToFullDC = 7
};

struct lsa_STRING {
        uint16_t Length;
        uint16_t MaximumLength;
        struct dcerpc_varying_bytes Buffer;
};

struct lsa_LSAPR_SECURITY_DESCRIPTOR {
        uint32_t Length;
        SECURITY_DESCRIPTOR * SecurityDescriptor;
};

enum lsa_SECURITY_IMPERSONATION_LEVEL {
        LSA_SecurityAnonymous = 0,
        LSA_SecurityIdentification = 1,
        LSA_SecurityImpersonation = 2,
        LSA_SecurityDelegation = 3
};

struct lsa_SECURITY_QUALITY_OF_SERVICE {
        uint32_t Length;
        enum lsa_SECURITY_IMPERSONATION_LEVEL ImpersonationLevel;
        uint8_t ContextTrackingMode;
        uint8_t EffectiveOnly;
};

struct lsa_LSAPR_OBJECT_ATTRIBUTES {
        uint32_t Length;
        uint8_t * RootDirectory;
        struct lsa_STRING * ObjectName;
        uint32_t Attributes;
        struct lsa_LSAPR_SECURITY_DESCRIPTOR * SecurityDescriptor;
        struct lsa_SECURITY_QUALITY_OF_SERVICE * SecurityQualityOfService;
};

struct lsa_LSAPR_SID_ENUM_BUFFER {
        uint32_t Entries;
        RPC_SID ** SidInfo;
};

struct lsa_LSAPR_TRUST_INFORMATION {
        char * Name;
        RPC_SID * Sid;
};

struct lsa_LSAPR_REFERENCED_DOMAIN_LIST {
        uint32_t Entries;
        struct lsa_LSAPR_TRUST_INFORMATION * Domains;
        uint32_t MaxEntries;
};

struct lsa_LSAPR_TRANSLATED_NAME_EX {
        uint32_t Use;
        char * Name;
        int32_t DomainIndex;
        uint32_t Flags;
};

struct lsa_LSAPR_TRANSLATED_NAMES_EX {
        uint32_t Entries;
        struct lsa_LSAPR_TRANSLATED_NAME_EX * Names;
};

struct lsa_LSAPR_TRANSLATED_SID_EX {
        uint32_t Use;
        uint32_t RelativeId;
        int32_t DomainIndex;
        uint32_t Flags;
};

struct lsa_LSAPR_TRANSLATED_SIDS_EX {
        uint32_t Entries;
        struct lsa_LSAPR_TRANSLATED_SID_EX * Sids;
};

struct lsa_Close_req {
        struct dcerpc_context_handle PolicyHandle;
};

struct lsa_Close_rep {
        struct dcerpc_context_handle PolicyHandle;
        uint32_t status;
};

struct lsa_OpenPolicy2_req {
        char * SystemName;
        struct lsa_LSAPR_OBJECT_ATTRIBUTES ObjectAttributes;
        uint32_t DesiredAccess;
};

struct lsa_OpenPolicy2_rep {
        struct dcerpc_context_handle PolicyHandle;
        uint32_t status;
};

struct lsa_LookupSids2_req {
        struct dcerpc_context_handle PolicyHandle;
        struct lsa_LSAPR_SID_ENUM_BUFFER SidEnumBuffer;
        struct lsa_LSAPR_TRANSLATED_NAMES_EX TranslatedNames;
        uint32_t LookupLevel;
        uint32_t MappedCount;
        uint32_t LookupOptions;
        uint32_t ClientRevision;
};

struct lsa_LookupSids2_rep {
        struct lsa_LSAPR_REFERENCED_DOMAIN_LIST ReferencedDomains;
        struct lsa_LSAPR_TRANSLATED_NAMES_EX TranslatedNames;
        uint32_t MappedCount;
        uint32_t status;
};

struct lsa_LookupNames2_req {
        struct dcerpc_context_handle PolicyHandle;
        uint32_t Count;
        char ** Names;
        struct lsa_LSAPR_TRANSLATED_SIDS_EX TranslatedSids;
        uint32_t LookupLevel;
        uint32_t MappedCount;
        uint32_t LookupOptions;
        uint32_t ClientRevision;
};

struct lsa_LookupNames2_rep {
        struct lsa_LSAPR_REFERENCED_DOMAIN_LIST ReferencedDomains;
        struct lsa_LSAPR_TRANSLATED_SIDS_EX TranslatedSids;
        uint32_t MappedCount;
        uint32_t status;
};

/* interface lsa uuid(12345778-1234-abcd-ef00-0123456789ab) version(0.0) */
extern p_syntax_id_t lsa_interface;

/* Named pipe (from the IDL endpoint) */
#define lsa_PIPE_NAME "lsarpc"

/* Operation numbers (wire opnum) */
#define LSA_CLOSE        0x00
#define LSA_OPENPOLICY2  0x2c
#define LSA_LOOKUPSIDS2  0x39
#define LSA_LOOKUPNAMES2 0x3a

/* Opnum → request/response coders, terminated by opnum -1 */
extern struct dcerpc_procedure lsa_procs[];

int lsa_POLICY_ACCESS_MASK_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int lsa_SID_NAME_USE_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int lsa_LSAP_LOOKUP_LEVEL_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int lsa_STRING_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_STRING_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int lsa_LSAPR_SECURITY_DESCRIPTOR_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_LSAPR_SECURITY_DESCRIPTOR_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int lsa_SECURITY_IMPERSONATION_LEVEL_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int lsa_SECURITY_QUALITY_OF_SERVICE_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_SECURITY_QUALITY_OF_SERVICE_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int lsa_LSAPR_OBJECT_ATTRIBUTES_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_LSAPR_OBJECT_ATTRIBUTES_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int lsa_LSAPR_SID_ENUM_BUFFER_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_LSAPR_SID_ENUM_BUFFER_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int lsa_LSAPR_TRUST_INFORMATION_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_LSAPR_TRUST_INFORMATION_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int lsa_LSAPR_REFERENCED_DOMAIN_LIST_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_LSAPR_REFERENCED_DOMAIN_LIST_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int lsa_LSAPR_TRANSLATED_NAME_EX_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_LSAPR_TRANSLATED_NAME_EX_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int lsa_LSAPR_TRANSLATED_NAMES_EX_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_LSAPR_TRANSLATED_NAMES_EX_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int lsa_LSAPR_TRANSLATED_SID_EX_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_LSAPR_TRANSLATED_SID_EX_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int lsa_LSAPR_TRANSLATED_SIDS_EX_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_LSAPR_TRANSLATED_SIDS_EX_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* Close opnum 0x00 (LSA_CLOSE) */
int lsa_Close_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_Close_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* OpenPolicy2 opnum 0x2c (LSA_OPENPOLICY2) */
int lsa_OpenPolicy2_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_OpenPolicy2_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* LookupSids2 opnum 0x39 (LSA_LOOKUPSIDS2) */
int lsa_LookupSids2_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_LookupSids2_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* LookupNames2 opnum 0x3a (LSA_LOOKUPNAMES2) */
int lsa_LookupNames2_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int lsa_LookupNames2_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);


#ifdef __cplusplus
}
#endif

#endif /* !_DCERPC_LSA_H_ */
