/* Auto-generated style prefix renames for libsmb2-internal DCE/RPC.
 * Include this before compiling dcerpc.c / dcerpc-srvsvc.c / smb2-share-enum.c
 * into libsmb2 so symbols do not clash with libdcerpc.
 */
#ifndef _LIBSMB2_DCERPC_PREFIX_H_
#define _LIBSMB2_DCERPC_PREFIX_H_

/*
 * Minimal NetrShareEnum path only: skip MS-DTYP types (SECURITY_DESCRIPTOR,
 * ACL, ACE, …) in public dcerpc headers. Those names collide with the Windows
 * SDK (winnt.h) when libsmb2 is built on Windows.
 */
#define LIBSMB2_DCERPC_MINIMAL 1

#define dcerpc_align_3264 libsmb2_dcerpc_align_3264
#define dcerpc_allocate_pdu libsmb2_dcerpc_allocate_pdu
#define dcerpc_alloc_data libsmb2_dcerpc_alloc_data
#define dcerpc_call libsmb2_dcerpc_call
#define dcerpc_call_async libsmb2_dcerpc_call_async
#define dcerpc_carray_coder libsmb2_dcerpc_carray_coder
#define dcerpc_connect_context libsmb2_dcerpc_connect_context
#define dcerpc_connect_context_async libsmb2_dcerpc_connect_context_async
#define dcerpc_context_handle_coder libsmb2_dcerpc_context_handle_coder
#define dcerpc_create_context libsmb2_dcerpc_create_context
#define dcerpc_create_context_smb libsmb2_dcerpc_create_context_smb
#define dcerpc_destroy_context libsmb2_dcerpc_destroy_context
#define dcerpc_do_coder libsmb2_dcerpc_do_coder
#define dcerpc_free_data libsmb2_dcerpc_free_data
#define dcerpc_free_pdu libsmb2_dcerpc_free_pdu
#define dcerpc_get_cr libsmb2_dcerpc_get_cr
#define dcerpc_get_error libsmb2_dcerpc_get_error
#define dcerpc_get_pdu_payload libsmb2_dcerpc_get_pdu_payload
#define dcerpc_get_request libsmb2_dcerpc_get_request
#define dcerpc_get_size_is libsmb2_dcerpc_get_size_is
#define dcerpc_get_smb2_context libsmb2_dcerpc_get_smb2_context
#define dcerpc_get_switch_is libsmb2_dcerpc_get_switch_is
#define dcerpc_get_unicode_max_length libsmb2_dcerpc_get_unicode_max_length
#define dcerpc_header_coder libsmb2_dcerpc_header_coder
#define dcerpc_json_next_key libsmb2_dcerpc_json_next_key
#define dcerpc_open_async libsmb2_dcerpc_open_async
#define dcerpc_pdu_clear_yaml_key libsmb2_dcerpc_pdu_clear_yaml_key
#define dcerpc_pdu_direction libsmb2_dcerpc_pdu_direction
#define dcerpc_pdu_encoding libsmb2_dcerpc_pdu_encoding
#define dcerpc_pdu_is_conformance_run libsmb2_dcerpc_pdu_is_conformance_run
#define dcerpc_pdu_json_key libsmb2_dcerpc_pdu_json_key
#define dcerpc_pdu_raise_max_alignment libsmb2_dcerpc_pdu_raise_max_alignment
#define dcerpc_pdu_yaml_key libsmb2_dcerpc_pdu_yaml_key
#define dcerpc_pdu_yaml_val libsmb2_dcerpc_pdu_yaml_val
#define dcerpc_ptr_coder libsmb2_dcerpc_ptr_coder
#define dcerpc_read_yaml_file libsmb2_dcerpc_read_yaml_file
#define dcerpc_RPC_UNICODE_STRING_coder libsmb2_dcerpc_RPC_UNICODE_STRING_coder
#define dcerpc_RPC_UNICODE_STRINGz_coder libsmb2_dcerpc_RPC_UNICODE_STRINGz_coder
#define dcerpc_services libsmb2_dcerpc_services
#define dcerpc_set_request libsmb2_dcerpc_set_request
#define dcerpc_set_size_is libsmb2_dcerpc_set_size_is
#define dcerpc_set_switch_is libsmb2_dcerpc_set_switch_is
#define dcerpc_set_uint8 libsmb2_dcerpc_set_uint8
#define dcerpc_set_unicode_max_length libsmb2_dcerpc_set_unicode_max_length
#define dcerpc_struct_coder libsmb2_dcerpc_struct_coder
#define dcerpc_uint16_coder libsmb2_dcerpc_uint16_coder
#define dcerpc_uint32_coder libsmb2_dcerpc_uint32_coder
#define dcerpc_uint32_coder_pp libsmb2_dcerpc_uint32_coder_pp
#define dcerpc_uint64_coder libsmb2_dcerpc_uint64_coder
#define dcerpc_union_coder libsmb2_dcerpc_union_coder
#define dcerpc_utf16_coder libsmb2_dcerpc_utf16_coder
#define dcerpc_utf16z_coder libsmb2_dcerpc_utf16z_coder
#define json_append libsmb2_json_append
#define json_append_quoted libsmb2_json_append_quoted
#define json_expect_key libsmb2_json_expect_key
#define json_parse_string libsmb2_json_parse_string
#define json_sep libsmb2_json_sep
#define ndr32_syntax libsmb2_ndr32_syntax
#define ndr64_syntax libsmb2_ndr64_syntax
#define ndr_carray_coder libsmb2_ndr_carray_coder
#define ndr_ptr_coder libsmb2_ndr_ptr_coder
#define ndr_set_endian libsmb2_ndr_set_endian
#define ndr_set_tctx libsmb2_ndr_set_tctx
#define ndr_struct_coder libsmb2_ndr_struct_coder
#define ndr_uint16_coder libsmb2_ndr_uint16_coder
#define ndr_uint3264_coder libsmb2_ndr_uint3264_coder
#define ndr_uint32_coder libsmb2_ndr_uint32_coder
#define ndr_uint8_coder libsmb2_ndr_uint8_coder
#define ndr_union_coder libsmb2_ndr_union_coder
#define ndr_utf16_coder libsmb2_ndr_utf16_coder
#define _ndr_utf16z_coder libsmb2__ndr_utf16z_coder
#define ndr_utf16z_coder libsmb2_ndr_utf16z_coder
#define ndr_uuid_coder libsmb2_ndr_uuid_coder
#define srvsvc_interface libsmb2_srvsvc_interface
#define srvsvc_NetrShareEnum_rep_coder libsmb2_srvsvc_NetrShareEnum_rep_coder
#define srvsvc_NetrShareEnum_req_coder libsmb2_srvsvc_NetrShareEnum_req_coder
#define srvsvc_procs libsmb2_srvsvc_procs
#define srvsvc_SHARE_ENUM_STRUCT_coder libsmb2_srvsvc_SHARE_ENUM_STRUCT_coder
#define srvsvc_SHARE_ENUM_STRUCT_struct_coder libsmb2_srvsvc_SHARE_ENUM_STRUCT_struct_coder
#define srvsvc_SHARE_INFO_0_coder libsmb2_srvsvc_SHARE_INFO_0_coder
#define srvsvc_SHARE_INFO_0_CONTAINER_coder libsmb2_srvsvc_SHARE_INFO_0_CONTAINER_coder
#define srvsvc_SHARE_INFO_0_STRUCT_coder libsmb2_srvsvc_SHARE_INFO_0_STRUCT_coder
#define srvsvc_SHARE_INFO_1_coder libsmb2_srvsvc_SHARE_INFO_1_coder
#define srvsvc_SHARE_INFO_1_CONTAINER_coder libsmb2_srvsvc_SHARE_INFO_1_CONTAINER_coder
#define srvsvc_SHARE_INFO_1_STRUCT_coder libsmb2_srvsvc_SHARE_INFO_1_STRUCT_coder
#define srvsvc_SHARE_INFO_2_coder libsmb2_srvsvc_SHARE_INFO_2_coder
#define srvsvc_SHARE_INFO_2_CONTAINER_coder libsmb2_srvsvc_SHARE_INFO_2_CONTAINER_coder
#define srvsvc_SHARE_INFO_2_STRUCT_coder libsmb2_srvsvc_SHARE_INFO_2_STRUCT_coder
#define yaml_next_kv libsmb2_yaml_next_kv
#define yaml_print_preamble libsmb2_yaml_print_preamble

#endif /* _LIBSMB2_DCERPC_PREFIX_H_ */
