/* -*-  mode:c; tab-width:8; c-basic-offset:8; indent-tabs-mode:nil;  -*- */
/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * AUTO-GENERATED by idlcomp.py from srvsvc.idl — do not edit.
 *
 * Types and coders are derived from the IDL; field names follow the IDL.
 */
#ifndef _DCERPC_SRVSVC_H_
#define _DCERPC_SRVSVC_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include <stdint.h>

#include <dcerpc/dcerpc.h>
#include <dcerpc/dcerpc-dtyp.h>

/* SRVSVC_HANDLE: UTF-16 string handle → char * */
/* CONNECTION_INFO_LEVEL: stored as uint32_t */
enum srvsvc_CONNECTION_INFO_LEVEL {
        SRVSVC_CONNECTION_INFO_0 = 0,
        SRVSVC_CONNECTION_INFO_1 = 1
};

/* FILE_INFO_LEVEL: stored as uint32_t */
enum srvsvc_FILE_INFO_LEVEL {
        SRVSVC_FILE_INFO_2 = 2,
        SRVSVC_FILE_INFO_3 = 3
};

/* SESSION_INFO_LEVEL: stored as uint32_t */
enum srvsvc_SESSION_INFO_LEVEL {
        SRVSVC_SESSION_INFO_0 = 0,
        SRVSVC_SESSION_INFO_1 = 1,
        SRVSVC_SESSION_INFO_2 = 2,
        SRVSVC_SESSION_INFO_10 = 10,
        SRVSVC_SESSION_INFO_502 = 502
};

/* SHARE_INFO_LEVEL: stored as uint32_t */
enum srvsvc_SHARE_INFO_LEVEL {
        SRVSVC_SHARE_INFO_0 = 0,
        SRVSVC_SHARE_INFO_1 = 1,
        SRVSVC_SHARE_INFO_2 = 2,
        SRVSVC_SHARE_INFO_501 = 501,
        SRVSVC_SHARE_INFO_502 = 502,
        SRVSVC_SHARE_INFO_503 = 503,
        SRVSVC_SHARE_INFO_1004 = 1004,
        SRVSVC_SHARE_INFO_1005 = 1005,
        SRVSVC_SHARE_INFO_1006 = 1006,
        SRVSVC_SHARE_INFO_1501 = 1501
};

/* SERVER_INFO_LEVEL: stored as uint32_t */
enum srvsvc_SERVER_INFO_LEVEL {
        SRVSVC_SERVER_INFO_100 = 100,
        SRVSVC_SERVER_INFO_101 = 101,
        SRVSVC_SERVER_INFO_102 = 102,
        SRVSVC_SERVER_INFO_103 = 103,
        SRVSVC_SERVER_INFO_502 = 502,
        SRVSVC_SERVER_INFO_503 = 503
};

/* STAT_SERVER_LEVEL: stored as uint32_t */
enum srvsvc_STAT_SERVER_LEVEL {
        SRVSVC_STAT_SERVER_0 = 0
};

/* SHARE_TYPE: bitmap, stored as uint32_t */
#define SRVSVC_STYPE_DISKTREE     0x00000000
#define SRVSVC_STYPE_PRINTQ       0x00000001
#define SRVSVC_STYPE_DEVICE       0x00000002
#define SRVSVC_STYPE_IPC          0x00000003
#define SRVSVC_STYPE_CLUSTER_FS   0x02000000
#define SRVSVC_STYPE_CLUSTER_SOFS 0x04000000
#define SRVSVC_STYPE_CLUSTER_DFS  0x08000000
#define SRVSVC_STYPE_TEMPORARY    0x40000000
#define SRVSVC_STYPE_SPECIAL      0x80000000U

/* SHARE_PERMISSIONS: bitmap, stored as uint32_t */
#define SRVSVC_ACCESS_READ   0x00000001
#define SRVSVC_ACCESS_WRITE  0x00000002
#define SRVSVC_ACCESS_CREATE 0x00000004
#define SRVSVC_ACCESS_EXEC   0x00000008
#define SRVSVC_ACCESS_DELETE 0x00000010
#define SRVSVC_ACCESS_ATRIB  0x00000020
#define SRVSVC_ACCESS_PERM   0x00000040

#define SRVSVC_ACCESS_ALL 0x0000007f

/* SHARE_FLAGS: bitmap, stored as uint32_t */
#define SRVSVC_SHI1005_FLAGS_DFS                         0x00000001
#define SRVSVC_SHI1005_FLAGS_DFS_ROOT                    0x00000002
#define SRVSVC_CSC_CACHE_MANUAL_REINT                    0x00000000
#define SRVSVC_CSC_CACHE_AUTO_REINT                      0x00000010
#define SRVSVC_CSC_CACHE_VDO                             0x00000020
#define SRVSVC_CSC_CACHE_NONE                            0x00000030
#define SRVSVC_SHI1005_FLAGS_RESTRICT_EXCLUSIVE_OPENS    0x00000100
#define SRVSVC_SHI1005_FLAGS_FORCE_SHARED_DELETE         0x00000200
#define SRVSVC_SHI1005_FLAGS_ALLOW_NAMESPACE_CACHING     0x00000400
#define SRVSVC_SHI1005_FLAGS_ACCESS_BASED_DIRECTORY_ENUM 0x00000800
#define SRVSVC_SHI1005_FLAGS_FORCE_LEVELII_OPLOCK        0x00001000
#define SRVSVC_SHI1005_FLAGS_ENABLE_HASH                 0x00002000
#define SRVSVC_SHI1005_FLAGS_ENABLE_CA                   0x00004000
#define SRVSVC_SHI1005_FLAGS_ENCRYPT_DATA                0x00008000
#define SRVSVC_SHI1005_FLAGS_RESERVED                    0x00010000
#define SRVSVC_SHI1005_FLAGS_DISABLE_CLIENT_BUFFERING    0x00020000
#define SRVSVC_SHI1005_FLAGS_IDENTITY_REMOTING           0x00040000
#define SRVSVC_SHI1005_FLAGS_CLUSTER_MANAGED             0x00080000
#define SRVSVC_SHI1005_FLAGS_COMPRESS_DATA               0x00100000

/* FILE_PERMISSIONS: bitmap, stored as uint32_t */
#define SRVSVC_PERM_FILE_READ   0x00000001
#define SRVSVC_PERM_FILE_WRITE  0x00000002
#define SRVSVC_PERM_FILE_CREATE 0x00000004

/* SESSION_USER_FLAGS: bitmap, stored as uint32_t */
#define SRVSVC_SESS_GUEST        0x00000001
#define SRVSVC_SESS_NOENCRYPTION 0x00000002

/* PLATFORM_ID: stored as uint32_t */
enum srvsvc_PLATFORM_ID {
        SRVSVC_PLATFORM_ID_DOS = 300,
        SRVSVC_PLATFORM_ID_OS2 = 400,
        SRVSVC_PLATFORM_ID_NT = 500,
        SRVSVC_PLATFORM_ID_OSF = 600,
        SRVSVC_PLATFORM_ID_VMS = 700
};

/* SV_TYPE: bitmap, stored as uint32_t */
#define SRVSVC_SV_TYPE_WORKSTATION       0x00000001
#define SRVSVC_SV_TYPE_SERVER            0x00000002
#define SRVSVC_SV_TYPE_SQLSERVER         0x00000004
#define SRVSVC_SV_TYPE_DOMAIN_CTRL       0x00000008
#define SRVSVC_SV_TYPE_DOMAIN_BAKCTRL    0x00000010
#define SRVSVC_SV_TYPE_TIME_SOURCE       0x00000020
#define SRVSVC_SV_TYPE_AFP               0x00000040
#define SRVSVC_SV_TYPE_NOVELL            0x00000080
#define SRVSVC_SV_TYPE_DOMAIN_MEMBER     0x00000100
#define SRVSVC_SV_TYPE_PRINTQ_SERVER     0x00000200
#define SRVSVC_SV_TYPE_DIALIN_SERVER     0x00000400
#define SRVSVC_SV_TYPE_XENIX_SERVER      0x00000800
#define SRVSVC_SV_TYPE_NT                0x00001000
#define SRVSVC_SV_TYPE_WFW               0x00002000
#define SRVSVC_SV_TYPE_SERVER_MFPN       0x00004000
#define SRVSVC_SV_TYPE_SERVER_NT         0x00008000
#define SRVSVC_SV_TYPE_POTENTIAL_BROWSER 0x00010000
#define SRVSVC_SV_TYPE_BACKUP_BROWSER    0x00020000
#define SRVSVC_SV_TYPE_MASTER_BROWSER    0x00040000
#define SRVSVC_SV_TYPE_DOMAIN_MASTER     0x00080000
#define SRVSVC_SV_TYPE_WINDOWS           0x00400000
#define SRVSVC_SV_TYPE_DFS               0x00800000
#define SRVSVC_SV_TYPE_CLUSTER_NT        0x01000000
#define SRVSVC_SV_TYPE_TERMINALSERVER    0x02000000
#define SRVSVC_SV_TYPE_CLUSTER_VS_NT     0x04000000
#define SRVSVC_SV_TYPE_DCE               0x10000000
#define SRVSVC_SV_TYPE_ALTERNATE_XPORT   0x20000000
#define SRVSVC_SV_TYPE_LOCAL_LIST_ONLY   0x40000000
#define SRVSVC_SV_TYPE_DOMAIN_ENUM       0x80000000U

struct srvsvc_CONNECTION_INFO_0 {
        uint32_t id;
};

struct srvsvc_CONNECT_INFO_0_CONTAINER {
        uint32_t EntriesRead;
        struct srvsvc_CONNECTION_INFO_0 * Buffer;
};

struct srvsvc_CONNECTION_INFO_1 {
        uint32_t id;
        uint32_t type;
        uint32_t num_opens;
        uint32_t num_users;
        uint32_t time;
        char * username;
        char * netname;
};

struct srvsvc_CONNECT_INFO_1_CONTAINER {
        uint32_t EntriesRead;
        struct srvsvc_CONNECTION_INFO_1 * Buffer;
};

union srvsvc_CONNECT_ENUM_UNION {
        struct srvsvc_CONNECT_INFO_0_CONTAINER Level0;
        struct srvsvc_CONNECT_INFO_1_CONTAINER Level1;
};

struct srvsvc_CONNECT_ENUM_STRUCT {
        uint32_t Level;
        union srvsvc_CONNECT_ENUM_UNION ConnectInfo;
};

struct srvsvc_FILE_INFO_2 {
        uint32_t id;
};

struct srvsvc_FILE_INFO_2_CONTAINER {
        uint32_t EntriesRead;
        struct srvsvc_FILE_INFO_2 * Buffer;
};

struct srvsvc_FILE_INFO_3 {
        uint32_t id;
        uint32_t permissions;
        uint32_t num_locks;
        char * pathname;
        char * username;
};

struct srvsvc_FILE_INFO_3_CONTAINER {
        uint32_t EntriesRead;
        struct srvsvc_FILE_INFO_3 * Buffer;
};

union srvsvc_FILE_ENUM_UNION {
        struct srvsvc_FILE_INFO_2_CONTAINER Level2;
        struct srvsvc_FILE_INFO_3_CONTAINER Level3;
};

struct srvsvc_FILE_ENUM_STRUCT {
        uint32_t Level;
        union srvsvc_FILE_ENUM_UNION FileInfo;
};

union srvsvc_FILE_INFO {
        struct srvsvc_FILE_INFO_2 FileInfo2;
        struct srvsvc_FILE_INFO_3 FileInfo3;
};

struct srvsvc_SESSION_INFO_0 {
        char * cname;
};

struct srvsvc_SESSION_INFO_0_CONTAINER {
        uint32_t EntriesRead;
        struct srvsvc_SESSION_INFO_0 * Buffer;
};

struct srvsvc_SESSION_INFO_1 {
        char * cname;
        char * username;
        uint32_t num_opens;
        uint32_t time;
        uint32_t idle_time;
        uint32_t user_flags;
};

struct srvsvc_SESSION_INFO_1_CONTAINER {
        uint32_t EntriesRead;
        struct srvsvc_SESSION_INFO_1 * Buffer;
};

struct srvsvc_SESSION_INFO_2 {
        char * cname;
        char * username;
        uint32_t num_opens;
        uint32_t time;
        uint32_t idle_time;
        uint32_t user_flags;
        char * cltype_name;
};

struct srvsvc_SESSION_INFO_2_CONTAINER {
        uint32_t EntriesRead;
        struct srvsvc_SESSION_INFO_2 * Buffer;
};

struct srvsvc_SESSION_INFO_10 {
        char * cname;
        char * username;
        uint32_t time;
        uint32_t idle_time;
};

struct srvsvc_SESSION_INFO_10_CONTAINER {
        uint32_t EntriesRead;
        struct srvsvc_SESSION_INFO_10 * Buffer;
};

struct srvsvc_SESSION_INFO_502 {
        char * cname;
        char * username;
        uint32_t num_opens;
        uint32_t time;
        uint32_t idle_time;
        uint32_t user_flags;
        char * cltype_name;
        char * transport;
};

struct srvsvc_SESSION_INFO_502_CONTAINER {
        uint32_t EntriesRead;
        struct srvsvc_SESSION_INFO_502 * Buffer;
};

union srvsvc_SESSION_ENUM_UNION {
        struct srvsvc_SESSION_INFO_0_CONTAINER Level0;
        struct srvsvc_SESSION_INFO_1_CONTAINER Level1;
        struct srvsvc_SESSION_INFO_2_CONTAINER Level2;
        struct srvsvc_SESSION_INFO_10_CONTAINER Level10;
        struct srvsvc_SESSION_INFO_502_CONTAINER Level502;
};

struct srvsvc_SESSION_ENUM_STRUCT {
        uint32_t Level;
        union srvsvc_SESSION_ENUM_UNION SessionInfo;
};

struct srvsvc_SHARE_INFO_0 {
        char * netname;
};

struct srvsvc_SHARE_INFO_0_CONTAINER {
        uint32_t EntriesRead;
        struct srvsvc_SHARE_INFO_0 * Buffer;
};

struct srvsvc_SHARE_INFO_1 {
        char * netname;
        uint32_t type;
        char * remark;
};

struct srvsvc_SHARE_INFO_1_CONTAINER {
        uint32_t EntriesRead;
        struct srvsvc_SHARE_INFO_1 * Buffer;
};

struct srvsvc_SHARE_INFO_2 {
        char * netname;
        uint32_t type;
        char * remark;
        uint32_t permissions;
        uint32_t max_uses;
        uint32_t current_uses;
        char * path;
        char * passwd;
};

struct srvsvc_SHARE_INFO_2_CONTAINER {
        uint32_t EntriesRead;
        struct srvsvc_SHARE_INFO_2 * Buffer;
};

struct srvsvc_SHARE_INFO_501 {
        char * netname;
        uint32_t type;
        char * remark;
        uint32_t flags;
};

struct srvsvc_SHARE_INFO_501_CONTAINER {
        uint32_t EntriesRead;
        struct srvsvc_SHARE_INFO_501 * Buffer;
};

struct srvsvc_SHARE_INFO_502_I {
        char * netname;
        uint32_t type;
        char * remark;
        uint32_t permissions;
        uint32_t max_uses;
        uint32_t current_uses;
        char * path;
        char * passwd;
        uint32_t reserved;
        SECURITY_DESCRIPTOR * security_descriptor;
};

struct srvsvc_SHARE_INFO_502_CONTAINER {
        uint32_t EntriesRead;
        struct srvsvc_SHARE_INFO_502_I * Buffer;
};

struct srvsvc_SHARE_INFO_503_I {
        char * netname;
        uint32_t type;
        char * remark;
        uint32_t permissions;
        uint32_t max_uses;
        uint32_t current_uses;
        char * path;
        char * passwd;
        char * servername;
        uint32_t reserved;
        SECURITY_DESCRIPTOR * security_descriptor;
};

struct srvsvc_SHARE_INFO_503_CONTAINER {
        uint32_t EntriesRead;
        struct srvsvc_SHARE_INFO_503_I * Buffer;
};

struct srvsvc_SHARE_INFO_1004 {
        char * remark;
};

struct srvsvc_SHARE_INFO_1005 {
        uint32_t flags;
};

struct srvsvc_SHARE_INFO_1006 {
        uint32_t max_uses;
};

struct srvsvc_SHARE_INFO_1501_I {
        uint32_t reserved;
        SECURITY_DESCRIPTOR * security_descriptor;
};

union srvsvc_SHARE_ENUM_UNION {
        struct srvsvc_SHARE_INFO_0_CONTAINER Level0;
        struct srvsvc_SHARE_INFO_1_CONTAINER Level1;
        struct srvsvc_SHARE_INFO_2_CONTAINER Level2;
        struct srvsvc_SHARE_INFO_501_CONTAINER Level501;
        struct srvsvc_SHARE_INFO_502_CONTAINER Level502;
        struct srvsvc_SHARE_INFO_503_CONTAINER Level503;
};

struct srvsvc_SHARE_ENUM_STRUCT {
        uint32_t Level;
        union srvsvc_SHARE_ENUM_UNION ShareInfo;
};

union srvsvc_SHARE_INFO {
        struct srvsvc_SHARE_INFO_0 ShareInfo0;
        struct srvsvc_SHARE_INFO_1 ShareInfo1;
        struct srvsvc_SHARE_INFO_2 ShareInfo2;
        struct srvsvc_SHARE_INFO_502_I ShareInfo502;
        struct srvsvc_SHARE_INFO_1004 ShareInfo1004;
        struct srvsvc_SHARE_INFO_1006 ShareInfo1006;
        struct srvsvc_SHARE_INFO_1501_I ShareInfo1501;
        struct srvsvc_SHARE_INFO_1005 ShareInfo1005;
        struct srvsvc_SHARE_INFO_501 ShareInfo501;
        struct srvsvc_SHARE_INFO_503_I ShareInfo503;
};

struct srvsvc_SERVER_INFO_100 {
        uint32_t platform_id;
        char * name;
};

struct srvsvc_SERVER_INFO_101 {
        uint32_t platform_id;
        char * name;
        uint32_t version_major;
        uint32_t version_minor;
        uint32_t type;
        char * comment;
};

struct srvsvc_SERVER_INFO_102 {
        uint32_t platform_id;
        char * name;
        uint32_t version_major;
        uint32_t version_minor;
        uint32_t type;
        char * comment;
        uint32_t users;
        int32_t disc;
        int32_t hidden;
        uint32_t announce;
        uint32_t anndelta;
        uint32_t licenses;
        char * userpath;
};

struct srvsvc_SERVER_INFO_103 {
        uint32_t platform_id;
        char * name;
        uint32_t version_major;
        uint32_t version_minor;
        uint32_t type;
        char * comment;
        uint32_t users;
        int32_t disc;
        int32_t hidden;
        uint32_t announce;
        uint32_t anndelta;
        uint32_t licenses;
        char * userpath;
        uint32_t capabilities;
};

struct srvsvc_SERVER_INFO_502 {
        uint32_t sessopens;
        uint32_t sessvcs;
        uint32_t opensearch;
        uint32_t sizreqbuf;
        uint32_t initworkitems;
        uint32_t maxworkitems;
        uint32_t rawworkitems;
        uint32_t irpstacksize;
        uint32_t maxrawbuflen;
        uint32_t sessusers;
        uint32_t sessconns;
        uint32_t maxpagedmemoryusage;
        uint32_t maxnonpagedmemoryusage;
        int32_t enablesoftcompat;
        int32_t enableforcedlogoff;
        int32_t timesource;
        int32_t acceptdownlevelapis;
        int32_t lmannounce;
};

struct srvsvc_SERVER_INFO_503 {
        uint32_t sessopens;
        uint32_t sessvcs;
        uint32_t opensearch;
        uint32_t sizreqbuf;
        uint32_t initworkitems;
        uint32_t maxworkitems;
        uint32_t rawworkitems;
        uint32_t irpstacksize;
        uint32_t maxrawbuflen;
        uint32_t sessusers;
        uint32_t sessconns;
        uint32_t maxpagedmemoryusage;
        uint32_t maxnonpagedmemoryusage;
        int32_t enablesoftcompat;
        int32_t enableforcedlogoff;
        int32_t timesource;
        int32_t acceptdownlevelapis;
        int32_t lmannounce;
        char * domain;
        uint32_t maxcopyreadlen;
        uint32_t maxcopywritelen;
        uint32_t minkeepsearch;
        uint32_t maxkeepsearch;
        uint32_t minkeepcomplsearch;
        uint32_t maxkeepcomplsearch;
        uint32_t threadcountadd;
        uint32_t numblockthreads;
        uint32_t scavtimeout;
        uint32_t minrcvqueue;
        uint32_t minfreeworkitems;
        uint32_t xactmemsize;
        uint32_t threadpriority;
        uint32_t maxmpxct;
        uint32_t oplockbreakwait;
        uint32_t oplockbreakresponsewait;
        int32_t enableoplocks;
        int32_t enableoplockforceclose;
        int32_t enablefcbopens;
        int32_t enableraw;
        int32_t enablesharednetdrives;
        uint32_t minfreeconnections;
        uint32_t maxfreeconnections;
};

union srvsvc_SERVER_INFO {
        struct srvsvc_SERVER_INFO_100 ServerInfo100;
        struct srvsvc_SERVER_INFO_101 ServerInfo101;
        struct srvsvc_SERVER_INFO_102 ServerInfo102;
        struct srvsvc_SERVER_INFO_103 ServerInfo103;
        struct srvsvc_SERVER_INFO_502 ServerInfo502;
        struct srvsvc_SERVER_INFO_503 ServerInfo503;
};

struct srvsvc_STAT_SERVER_0 {
        uint32_t start;
        uint32_t fopens;
        uint32_t devopens;
        uint32_t jobsqueued;
        uint32_t sopens;
        uint32_t stimedout;
        uint32_t serrorout;
        uint32_t pwerrors;
        uint32_t permerrors;
        uint32_t syserrors;
        uint32_t bytessent_low;
        uint32_t bytessent_high;
        uint32_t bytesrcvd_low;
        uint32_t bytesrcvd_high;
        uint32_t avresponse;
        uint32_t reqbufneed;
        uint32_t bigbufneed;
};

struct srvsvc_TIME_OF_DAY_INFO {
        uint32_t elapsedt;
        uint32_t msecs;
        uint32_t hours;
        uint32_t mins;
        uint32_t secs;
        uint32_t hunds;
        int32_t timezone;
        uint32_t tinterval;
        uint32_t day;
        uint32_t month;
        uint32_t year;
        uint32_t weekday;
};

struct srvsvc_NetrConnectionEnum_req {
        char * ServerName;
        char * Qualifier;
        struct srvsvc_CONNECT_ENUM_STRUCT InfoStruct;
        uint32_t PreferedMaximumLength;
        uint32_t ResumeHandle;
};

struct srvsvc_NetrConnectionEnum_rep {
        struct srvsvc_CONNECT_ENUM_STRUCT InfoStruct;
        uint32_t TotalEntries;
        uint32_t ResumeHandle;
        uint32_t status;
};

struct srvsvc_NetrFileEnum_req {
        char * ServerName;
        char * BasePath;
        char * UserName;
        struct srvsvc_FILE_ENUM_STRUCT InfoStruct;
        uint32_t PreferedMaximumLength;
        uint32_t ResumeHandle;
};

struct srvsvc_NetrFileEnum_rep {
        struct srvsvc_FILE_ENUM_STRUCT InfoStruct;
        uint32_t TotalEntries;
        uint32_t ResumeHandle;
        uint32_t status;
};

struct srvsvc_NetrFileGetInfo_req {
        char * ServerName;
        uint32_t FileId;
        uint32_t Level;
};

struct srvsvc_NetrFileGetInfo_rep {
        union srvsvc_FILE_INFO InfoStruct;
        uint32_t status;
};

struct srvsvc_NetrFileClose_req {
        char * ServerName;
        uint32_t FileId;
};

struct srvsvc_NetrFileClose_rep {
        uint32_t status;
};

struct srvsvc_NetrSessionEnum_req {
        char * ServerName;
        char * ClientName;
        char * UserName;
        struct srvsvc_SESSION_ENUM_STRUCT InfoStruct;
        uint32_t PreferedMaximumLength;
        uint32_t ResumeHandle;
};

struct srvsvc_NetrSessionEnum_rep {
        struct srvsvc_SESSION_ENUM_STRUCT InfoStruct;
        uint32_t TotalEntries;
        uint32_t ResumeHandle;
        uint32_t status;
};

struct srvsvc_NetrSessionDel_req {
        char * ServerName;
        char * ClientName;
        char * UserName;
};

struct srvsvc_NetrSessionDel_rep {
        uint32_t status;
};

struct srvsvc_NetrShareAdd_req {
        char * ServerName;
        uint32_t Level;
        union srvsvc_SHARE_INFO InfoStruct;
        uint32_t ParmErr;
};

struct srvsvc_NetrShareAdd_rep {
        uint32_t ParmErr;
        uint32_t status;
};

struct srvsvc_NetrShareEnum_req {
        char * ServerName;
        struct srvsvc_SHARE_ENUM_STRUCT InfoStruct;
        uint32_t PreferedMaximumLength;
        uint32_t ResumeHandle;
};

struct srvsvc_NetrShareEnum_rep {
        struct srvsvc_SHARE_ENUM_STRUCT InfoStruct;
        uint32_t TotalEntries;
        uint32_t ResumeHandle;
        uint32_t status;
};

struct srvsvc_NetrShareGetInfo_req {
        char * ServerName;
        char * NetName;
        uint32_t Level;
};

struct srvsvc_NetrShareGetInfo_rep {
        union srvsvc_SHARE_INFO InfoStruct;
        uint32_t status;
};

struct srvsvc_NetrShareSetInfo_req {
        char * ServerName;
        char * NetName;
        uint32_t Level;
        union srvsvc_SHARE_INFO ShareInfo;
        uint32_t ParmErr;
};

struct srvsvc_NetrShareSetInfo_rep {
        uint32_t ParmErr;
        uint32_t status;
};

struct srvsvc_NetrShareDel_req {
        char * ServerName;
        char * NetName;
        uint32_t Reserved;
};

struct srvsvc_NetrShareDel_rep {
        uint32_t status;
};

struct srvsvc_NetrShareDelSticky_req {
        char * ServerName;
        char * NetName;
        uint32_t Reserved;
};

struct srvsvc_NetrShareDelSticky_rep {
        uint32_t status;
};

struct srvsvc_NetrShareCheck_req {
        char * ServerName;
        char * Device;
};

struct srvsvc_NetrShareCheck_rep {
        uint32_t Type;
        uint32_t status;
};

struct srvsvc_NetrServerGetInfo_req {
        char * ServerName;
        uint32_t Level;
};

struct srvsvc_NetrServerGetInfo_rep {
        union srvsvc_SERVER_INFO InfoStruct;
        uint32_t status;
};

struct srvsvc_NetrServerSetInfo_req {
        char * ServerName;
        uint32_t Level;
        union srvsvc_SERVER_INFO ServerInfo;
        uint32_t ParmError;
};

struct srvsvc_NetrServerSetInfo_rep {
        uint32_t ParmError;
        uint32_t status;
};

struct srvsvc_NetrServerStatisticsGet_req {
        char * ServerName;
        char * Service;
        uint32_t Level;
        uint32_t Options;
};

struct srvsvc_NetrServerStatisticsGet_rep {
        struct srvsvc_STAT_SERVER_0 InfoStruct;
        uint32_t status;
};

struct srvsvc_NetrRemoteTOD_req {
        char * ServerName;
};

struct srvsvc_NetrRemoteTOD_rep {
        struct srvsvc_TIME_OF_DAY_INFO BufferPtr;
        uint32_t status;
};

/* interface srvsvc uuid(4b324fc8-1670-01d3-1278-5a47bf6ee188) version(3.0) */
extern p_syntax_id_t srvsvc_interface;

/* Named pipe (from the IDL endpoint) */
#define srvsvc_PIPE_NAME "srvsvc"

/* Operation numbers (wire opnum) */
#define SRVSVC_NETRCONNECTIONENUM      0x08
#define SRVSVC_NETRFILEENUM            0x09
#define SRVSVC_NETRFILEGETINFO         0x0a
#define SRVSVC_NETRFILECLOSE           0x0b
#define SRVSVC_NETRSESSIONENUM         0x0c
#define SRVSVC_NETRSESSIONDEL          0x0d
#define SRVSVC_NETRSHAREADD            0x0e
#define SRVSVC_NETRSHAREENUM           0x0f
#define SRVSVC_NETRSHAREGETINFO        0x10
#define SRVSVC_NETRSHARESETINFO        0x11
#define SRVSVC_NETRSHAREDEL            0x12
#define SRVSVC_NETRSHAREDELSTICKY      0x13
#define SRVSVC_NETRSHARECHECK          0x14
#define SRVSVC_NETRSERVERGETINFO       0x15
#define SRVSVC_NETRSERVERSETINFO       0x16
#define SRVSVC_NETRSERVERSTATISTICSGET 0x18
#define SRVSVC_NETRREMOTETOD           0x1c

/* Opnum → request/response coders, terminated by opnum -1 */
extern struct dcerpc_procedure srvsvc_procs[];

int srvsvc_CONNECTION_INFO_LEVEL_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_FILE_INFO_LEVEL_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SESSION_INFO_LEVEL_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_LEVEL_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SERVER_INFO_LEVEL_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_STAT_SERVER_LEVEL_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_TYPE_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_PERMISSIONS_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_FLAGS_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_FILE_PERMISSIONS_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SESSION_USER_FLAGS_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_PLATFORM_ID_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SV_TYPE_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_CONNECTION_INFO_0_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_CONNECTION_INFO_0_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_CONNECT_INFO_0_CONTAINER_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_CONNECT_INFO_0_CONTAINER_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_CONNECTION_INFO_1_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_CONNECTION_INFO_1_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_CONNECT_INFO_1_CONTAINER_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_CONNECT_INFO_1_CONTAINER_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_CONNECT_ENUM_UNION_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_CONNECT_ENUM_STRUCT_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_CONNECT_ENUM_STRUCT_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_FILE_INFO_2_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_FILE_INFO_2_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_FILE_INFO_2_CONTAINER_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_FILE_INFO_2_CONTAINER_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_FILE_INFO_3_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_FILE_INFO_3_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_FILE_INFO_3_CONTAINER_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_FILE_INFO_3_CONTAINER_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_FILE_ENUM_UNION_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_FILE_ENUM_STRUCT_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_FILE_ENUM_STRUCT_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_FILE_INFO_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_FILE_INFO_switch_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SESSION_INFO_0_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SESSION_INFO_0_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SESSION_INFO_0_CONTAINER_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SESSION_INFO_0_CONTAINER_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SESSION_INFO_1_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SESSION_INFO_1_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SESSION_INFO_1_CONTAINER_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SESSION_INFO_1_CONTAINER_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SESSION_INFO_2_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SESSION_INFO_2_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SESSION_INFO_2_CONTAINER_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SESSION_INFO_2_CONTAINER_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SESSION_INFO_10_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SESSION_INFO_10_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SESSION_INFO_10_CONTAINER_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SESSION_INFO_10_CONTAINER_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SESSION_INFO_502_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SESSION_INFO_502_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SESSION_INFO_502_CONTAINER_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SESSION_INFO_502_CONTAINER_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SESSION_ENUM_UNION_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SESSION_ENUM_STRUCT_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SESSION_ENUM_STRUCT_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_0_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_INFO_0_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_0_CONTAINER_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_INFO_0_CONTAINER_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_1_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_INFO_1_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_1_CONTAINER_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_INFO_1_CONTAINER_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_2_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_INFO_2_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_2_CONTAINER_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_INFO_2_CONTAINER_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_501_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_INFO_501_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_501_CONTAINER_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_INFO_501_CONTAINER_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_502_I_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_INFO_502_I_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_502_CONTAINER_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_INFO_502_CONTAINER_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_503_I_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_INFO_503_I_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_503_CONTAINER_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_INFO_503_CONTAINER_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_1004_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_INFO_1004_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_1005_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_INFO_1005_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_1006_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_INFO_1006_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_1501_I_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_INFO_1501_I_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_ENUM_UNION_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_ENUM_STRUCT_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_ENUM_STRUCT_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SHARE_INFO_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SHARE_INFO_switch_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SERVER_INFO_100_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SERVER_INFO_100_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SERVER_INFO_101_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SERVER_INFO_101_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SERVER_INFO_102_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SERVER_INFO_102_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SERVER_INFO_103_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SERVER_INFO_103_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SERVER_INFO_502_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SERVER_INFO_502_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SERVER_INFO_503_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SERVER_INFO_503_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_SERVER_INFO_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_SERVER_INFO_switch_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_STAT_SERVER_0_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_STAT_SERVER_0_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int srvsvc_TIME_OF_DAY_INFO_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_TIME_OF_DAY_INFO_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* NetrConnectionEnum opnum 0x08 (SRVSVC_NETRCONNECTIONENUM) */
int srvsvc_NetrConnectionEnum_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_NetrConnectionEnum_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* NetrFileEnum opnum 0x09 (SRVSVC_NETRFILEENUM) */
int srvsvc_NetrFileEnum_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_NetrFileEnum_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* NetrFileGetInfo opnum 0x0a (SRVSVC_NETRFILEGETINFO) */
int srvsvc_NetrFileGetInfo_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_NetrFileGetInfo_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* NetrFileClose opnum 0x0b (SRVSVC_NETRFILECLOSE) */
int srvsvc_NetrFileClose_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_NetrFileClose_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* NetrSessionEnum opnum 0x0c (SRVSVC_NETRSESSIONENUM) */
int srvsvc_NetrSessionEnum_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_NetrSessionEnum_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* NetrSessionDel opnum 0x0d (SRVSVC_NETRSESSIONDEL) */
int srvsvc_NetrSessionDel_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_NetrSessionDel_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* NetrShareAdd opnum 0x0e (SRVSVC_NETRSHAREADD) */
int srvsvc_NetrShareAdd_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_NetrShareAdd_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* NetrShareEnum opnum 0x0f (SRVSVC_NETRSHAREENUM) */
int srvsvc_NetrShareEnum_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_NetrShareEnum_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* NetrShareGetInfo opnum 0x10 (SRVSVC_NETRSHAREGETINFO) */
int srvsvc_NetrShareGetInfo_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_NetrShareGetInfo_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* NetrShareSetInfo opnum 0x11 (SRVSVC_NETRSHARESETINFO) */
int srvsvc_NetrShareSetInfo_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_NetrShareSetInfo_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* NetrShareDel opnum 0x12 (SRVSVC_NETRSHAREDEL) */
int srvsvc_NetrShareDel_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_NetrShareDel_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* NetrShareDelSticky opnum 0x13 (SRVSVC_NETRSHAREDELSTICKY) */
int srvsvc_NetrShareDelSticky_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_NetrShareDelSticky_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* NetrShareCheck opnum 0x14 (SRVSVC_NETRSHARECHECK) */
int srvsvc_NetrShareCheck_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_NetrShareCheck_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* NetrServerGetInfo opnum 0x15 (SRVSVC_NETRSERVERGETINFO) */
int srvsvc_NetrServerGetInfo_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_NetrServerGetInfo_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* NetrServerSetInfo opnum 0x16 (SRVSVC_NETRSERVERSETINFO) */
int srvsvc_NetrServerSetInfo_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_NetrServerSetInfo_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* NetrServerStatisticsGet opnum 0x18 (SRVSVC_NETRSERVERSTATISTICSGET) */
int srvsvc_NetrServerStatisticsGet_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_NetrServerStatisticsGet_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* NetrRemoteTOD opnum 0x1c (SRVSVC_NETRREMOTETOD) */
int srvsvc_NetrRemoteTOD_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int srvsvc_NetrRemoteTOD_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);


#ifdef __cplusplus
}
#endif

#endif /* !_DCERPC_SRVSVC_H_ */
