/* -*-  mode:c; tab-width:8; c-basic-offset:8; indent-tabs-mode:nil;  -*- */
/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * AUTO-GENERATED by idlcomp.py from winreg.idl — do not edit.
 *
 * Types and coders are derived from the IDL; field names follow the IDL.
 */
#ifndef _DCERPC_WINREG_H_
#define _DCERPC_WINREG_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include <stdint.h>

#include <dcerpc/dcerpc.h>

/* REGSAM: bitmap, stored as uint32_t */
#define WINREG_KEY_QUERY_VALUE        0x00000001
#define WINREG_KEY_SET_VALUE          0x00000002
#define WINREG_KEY_CREATE_SUB_KEY     0x00000004
#define WINREG_KEY_ENUMERATE_SUB_KEYS 0x00000008
#define WINREG_KEY_NOTIFY             0x00000010
#define WINREG_KEY_CREATE_LINK        0x00000020
#define WINREG_KEY_WOW64_64KEY        0x00000100
#define WINREG_KEY_WOW64_32KEY        0x00000200
#define WINREG_DELETE                 0x00010000
#define WINREG_READ_CONTROL           0x00020000
#define WINREG_WRITE_DAC              0x00040000
#define WINREG_WRITE_OWNER            0x00080000
#define WINREG_SYNCHRONIZE            0x00100000
#define WINREG_KEY_READ               0x00020019
#define WINREG_KEY_WRITE              0x00020006
#define WINREG_KEY_ALL_ACCESS         0x000f003f

/* REG_OPTIONS: bitmap, stored as uint32_t */
#define WINREG_REG_OPTION_NON_VOLATILE   0x00000000
#define WINREG_REG_OPTION_VOLATILE       0x00000001
#define WINREG_REG_OPTION_CREATE_LINK    0x00000002
#define WINREG_REG_OPTION_BACKUP_RESTORE 0x00000004
#define WINREG_REG_OPTION_OPEN_LINK      0x00000008

/* REG_DISPOSITION: stored as uint32_t */
enum winreg_REG_DISPOSITION {
        WINREG_REG_CREATED_NEW_KEY = 1,
        WINREG_REG_OPENED_EXISTING_KEY = 2
};

/* REG_VALUE_TYPE: stored as uint32_t */
enum winreg_REG_VALUE_TYPE {
        WINREG_REG_NONE = 0,
        WINREG_REG_SZ = 1,
        WINREG_REG_EXPAND_SZ = 2,
        WINREG_REG_BINARY = 3,
        WINREG_REG_DWORD = 4,
        WINREG_REG_DWORD_BIG_ENDIAN = 5,
        WINREG_REG_LINK = 6,
        WINREG_REG_MULTI_SZ = 7,
        WINREG_REG_RESOURCE_LIST = 8,
        WINREG_REG_FULL_RESOURCE_DESCRIPTOR = 9,
        WINREG_REG_RESOURCE_REQUIREMENTS_LIST = 10,
        WINREG_REG_QWORD = 11
};

struct winreg_FILETIME {
        uint32_t dwLowDateTime;
        uint32_t dwHighDateTime;
};

struct winreg_RPC_SECURITY_DESCRIPTOR {
        struct dcerpc_varying_bytes lpSecurityDescriptor;
        uint32_t cbInSecurityDescriptor;
        uint32_t cbOutSecurityDescriptor;
};

struct winreg_RPC_SECURITY_ATTRIBUTES {
        uint32_t nLength;
        struct winreg_RPC_SECURITY_DESCRIPTOR RpcSecurityDescriptor;
        uint8_t bInheritHandle;
};

struct winreg_OpenClassesRoot_req {
        uint16_t * ServerName;
        uint32_t samDesired;
};

struct winreg_OpenClassesRoot_rep {
        struct dcerpc_context_handle phKey;
        uint32_t status;
};

struct winreg_OpenCurrentUser_req {
        uint16_t * ServerName;
        uint32_t samDesired;
};

struct winreg_OpenCurrentUser_rep {
        struct dcerpc_context_handle phKey;
        uint32_t status;
};

struct winreg_OpenLocalMachine_req {
        uint16_t * ServerName;
        uint32_t samDesired;
};

struct winreg_OpenLocalMachine_rep {
        struct dcerpc_context_handle phKey;
        uint32_t status;
};

struct winreg_OpenUsers_req {
        uint16_t * ServerName;
        uint32_t samDesired;
};

struct winreg_OpenUsers_rep {
        struct dcerpc_context_handle phKey;
        uint32_t status;
};

struct winreg_BaseRegCloseKey_req {
        struct dcerpc_context_handle hKey;
};

struct winreg_BaseRegCloseKey_rep {
        struct dcerpc_context_handle hKey;
        uint32_t status;
};

struct winreg_BaseRegCreateKey_req {
        struct dcerpc_context_handle hKey;
        char * lpSubKey;
        char * lpClass;
        uint32_t dwOptions;
        uint32_t samDesired;
        struct winreg_RPC_SECURITY_ATTRIBUTES * lpSecurityAttributes;
        uint32_t lpdwDisposition;
};

struct winreg_BaseRegCreateKey_rep {
        struct dcerpc_context_handle phkResult;
        uint32_t lpdwDisposition;
        uint32_t status;
};

struct winreg_BaseRegDeleteKey_req {
        struct dcerpc_context_handle hKey;
        char * lpSubKey;
};

struct winreg_BaseRegDeleteKey_rep {
        uint32_t status;
};

struct winreg_BaseRegDeleteValue_req {
        struct dcerpc_context_handle hKey;
        char * lpValueName;
};

struct winreg_BaseRegDeleteValue_rep {
        uint32_t status;
};

struct winreg_BaseRegEnumKey_req {
        struct dcerpc_context_handle hKey;
        uint32_t dwIndex;
        char * lpNameIn;
        char * lpClassIn;
        struct winreg_FILETIME * lpftLastWriteTime;
};

struct winreg_BaseRegEnumKey_rep {
        char * lpNameOut;
        char * lplpClassOut;
        struct winreg_FILETIME * lpftLastWriteTime;
        uint32_t status;
};

struct winreg_BaseRegEnumValue_req {
        struct dcerpc_context_handle hKey;
        uint32_t dwIndex;
        char * lpValueNameIn;
        uint32_t lpType;
        uint8_t * lpData;
        uint32_t lpcbData;
        uint32_t lpcbLen;
};

struct winreg_BaseRegEnumValue_rep {
        char * lpValueNameOut;
        uint32_t lpType;
        uint8_t * lpData;
        uint32_t lpcbData;
        uint32_t lpcbLen;
        uint32_t status;
};

struct winreg_BaseRegOpenKey_req {
        struct dcerpc_context_handle hKey;
        char * lpSubKey;
        uint32_t dwOptions;
        uint32_t samDesired;
};

struct winreg_BaseRegOpenKey_rep {
        struct dcerpc_context_handle phkResult;
        uint32_t status;
};

struct winreg_BaseRegQueryInfoKey_req {
        struct dcerpc_context_handle hKey;
        char * lpClassIn;
};

struct winreg_BaseRegQueryInfoKey_rep {
        char * lpClassOut;
        uint32_t lpcSubKeys;
        uint32_t lpcbMaxSubKeyLen;
        uint32_t lpcbMaxClassLen;
        uint32_t lpcValues;
        uint32_t lpcbMaxValueNameLen;
        uint32_t lpcbMaxValueLen;
        uint32_t lpcbSecurityDescriptor;
        struct winreg_FILETIME lpftLastWriteTime;
        uint32_t status;
};

struct winreg_BaseRegSetValue_req {
        struct dcerpc_context_handle hKey;
        char * lpValueName;
        uint32_t dwType;
        uint8_t * lpData;
        uint32_t cbData;
};

struct winreg_BaseRegSetValue_rep {
        uint32_t status;
};

struct winreg_OpenCurrentConfig_req {
        uint16_t * ServerName;
        uint32_t samDesired;
};

struct winreg_OpenCurrentConfig_rep {
        struct dcerpc_context_handle phKey;
        uint32_t status;
};

/* interface winreg uuid(338cd001-2244-31f1-aaaa-900038001003) version(1.0) */
extern p_syntax_id_t winreg_interface;

/* Named pipe (from the IDL endpoint) */
#define winreg_PIPE_NAME "winreg"

/* Operation numbers (wire opnum) */
#define WINREG_OPENCLASSESROOT     0x00
#define WINREG_OPENCURRENTUSER     0x01
#define WINREG_OPENLOCALMACHINE    0x02
#define WINREG_OPENUSERS           0x04
#define WINREG_BASEREGCLOSEKEY     0x05
#define WINREG_BASEREGCREATEKEY    0x06
#define WINREG_BASEREGDELETEKEY    0x07
#define WINREG_BASEREGDELETEVALUE  0x08
#define WINREG_BASEREGENUMKEY      0x09
#define WINREG_BASEREGENUMVALUE    0x0a
#define WINREG_BASEREGOPENKEY      0x0f
#define WINREG_BASEREGQUERYINFOKEY 0x10
#define WINREG_BASEREGSETVALUE     0x16
#define WINREG_OPENCURRENTCONFIG   0x1b

/* Opnum → request/response coders, terminated by opnum -1 */
extern struct dcerpc_procedure winreg_procs[];

int winreg_REGSAM_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int winreg_REG_OPTIONS_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int winreg_REG_DISPOSITION_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int winreg_REG_VALUE_TYPE_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int winreg_FILETIME_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int winreg_FILETIME_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int winreg_RPC_SECURITY_DESCRIPTOR_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int winreg_RPC_SECURITY_DESCRIPTOR_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

int winreg_RPC_SECURITY_ATTRIBUTES_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int winreg_RPC_SECURITY_ATTRIBUTES_struct_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* OpenClassesRoot opnum 0x00 (WINREG_OPENCLASSESROOT) */
int winreg_OpenClassesRoot_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int winreg_OpenClassesRoot_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* OpenCurrentUser opnum 0x01 (WINREG_OPENCURRENTUSER) */
int winreg_OpenCurrentUser_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int winreg_OpenCurrentUser_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* OpenLocalMachine opnum 0x02 (WINREG_OPENLOCALMACHINE) */
int winreg_OpenLocalMachine_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int winreg_OpenLocalMachine_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* OpenUsers opnum 0x04 (WINREG_OPENUSERS) */
int winreg_OpenUsers_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int winreg_OpenUsers_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* BaseRegCloseKey opnum 0x05 (WINREG_BASEREGCLOSEKEY) */
int winreg_BaseRegCloseKey_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int winreg_BaseRegCloseKey_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* BaseRegCreateKey opnum 0x06 (WINREG_BASEREGCREATEKEY) */
int winreg_BaseRegCreateKey_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int winreg_BaseRegCreateKey_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* BaseRegDeleteKey opnum 0x07 (WINREG_BASEREGDELETEKEY) */
int winreg_BaseRegDeleteKey_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int winreg_BaseRegDeleteKey_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* BaseRegDeleteValue opnum 0x08 (WINREG_BASEREGDELETEVALUE) */
int winreg_BaseRegDeleteValue_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int winreg_BaseRegDeleteValue_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* BaseRegEnumKey opnum 0x09 (WINREG_BASEREGENUMKEY) */
int winreg_BaseRegEnumKey_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int winreg_BaseRegEnumKey_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* BaseRegEnumValue opnum 0x0a (WINREG_BASEREGENUMVALUE) */
int winreg_BaseRegEnumValue_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int winreg_BaseRegEnumValue_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* BaseRegOpenKey opnum 0x0f (WINREG_BASEREGOPENKEY) */
int winreg_BaseRegOpenKey_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int winreg_BaseRegOpenKey_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* BaseRegQueryInfoKey opnum 0x10 (WINREG_BASEREGQUERYINFOKEY) */
int winreg_BaseRegQueryInfoKey_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int winreg_BaseRegQueryInfoKey_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* BaseRegSetValue opnum 0x16 (WINREG_BASEREGSETVALUE) */
int winreg_BaseRegSetValue_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int winreg_BaseRegSetValue_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);

/* OpenCurrentConfig opnum 0x1b (WINREG_OPENCURRENTCONFIG) */
int winreg_OpenCurrentConfig_req_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);
int winreg_OpenCurrentConfig_rep_coder(char *name, struct dcerpc_context *dce,
                struct dcerpc_pdu *pdu, struct dcerpc_iovec *iov,
                int *offset, void *ptr);


#ifdef __cplusplus
}
#endif

#endif /* !_DCERPC_WINREG_H_ */
