name: CI-compile

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fjtrujy/ps2dev:latest
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip gawk
    
    - name: git checkout
      uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    
    - name:  make 
      run: |
        make
  
    - name: Upload release artifact H
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: NTFS
        path: |
          ntfs.h
   
  
